If you're opening this Notebook on colab, you will probably need to install 🤗 Transformers and 🤗 Datasets. Uncomment the following cell and run it.

In [ ]:
! pip install datasets transformers
#!pip install datasets==4.8.4
#!pip install transformers
!pip install --upgrade datasets

Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.13.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.29.7)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.8.1)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (1.23.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.26.8)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.8.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.14.1)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2026.6.17)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2026.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.24.2)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (4.14.2)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Collecting datasets
  Downloading datasets-5.0.0-py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.29.7)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.0.2)
Collecting pyarrow>=21.0.0 (from datasets)
  Downloading pyarrow-25.0.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.8.1)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2026.4.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (1.23.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (3.14.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.5.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2026.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.24.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Downloading datasets-5.0.0-py3-none-any.whl (555 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 555.1/555.1 kB 17.6 MB/s eta 0:00:00
Downloading pyarrow-25.0.0-cp312-cp312-manylinux_2_28_x86_64.whl (50.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 MB 20.3 MB/s eta 0:00:00
Installing collected packages: pyarrow, datasets
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 18.1.0
    Uninstalling pyarrow-18.1.0:
      Successfully uninstalled pyarrow-18.1.0
  Attempting uninstall: datasets
    Found existing installation: datasets 4.0.0
    Uninstalling datasets-4.0.0:
      Successfully uninstalled datasets-4.0.0
Successfully installed datasets-5.0.0 pyarrow-25.0.0

If you're opening this notebook locally, make sure your environment has an install from the last version of those libraries.

In [ ]:
#from huggingface_hub import notebook_login

#notebook_login()

In [ ]:
#!apt install git-lfs
!pip install torch

Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.13.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch) (3.29.7)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.16.0)
Requirement already satisfied: setuptools>=77.0.3 in /usr/local/lib/python3.12/dist-packages (from torch) (83.0.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: cuda-toolkit==13.0.3 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch) (13.0.3.0)
Requirement already satisfied: cuda-bindings<14,>=13.0.3 in /usr/local/lib/python3.12/dist-packages (from torch) (13.3.1)
Requirement already satisfied: nvidia-cudnn-cu13==9.20.0.48 in /usr/local/lib/python3.12/dist-packages (from torch) (9.20.0.48)
Requirement already satisfied: nvidia-cusparselt-cu13==0.8.1 in /usr/local/lib/python3.12/dist-packages (from torch) (0.8.1)
Requirement already satisfied: nvidia-nccl-cu13==2.29.7 in /usr/local/lib/python3.12/dist-packages (from torch) (2.29.7)
Requirement already satisfied: nvidia-nvshmem-cu13==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch) (3.4.5)
Requirement already satisfied: triton==3.7.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.7.1)
Requirement already satisfied: nvidia-cublas==13.1.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch) (13.1.1.3)
Requirement already satisfied: nvidia-cuda-nvrtc==13.0.88.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch) (13.0.88)
Requirement already satisfied: nvidia-cuda-runtime==13.0.96.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch) (13.0.96)
Requirement already satisfied: nvidia-cufft==12.0.0.61.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch) (12.0.0.61)
Requirement already satisfied: nvidia-nvjitlink<14,>=13.0.88 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch) (13.3.33)
Requirement already satisfied: nvidia-cufile==1.15.1.6.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch) (1.15.1.6)
Requirement already satisfied: nvidia-cuda-cupti==13.0.85.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch) (13.0.85)
Requirement already satisfied: nvidia-curand==10.4.0.35.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch) (10.4.0.35)
Requirement already satisfied: nvidia-cusolver==12.0.4.66.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch) (12.0.4.66)
Requirement already satisfied: nvidia-cusparse==12.6.3.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch) (12.6.3.3)
Requirement already satisfied: nvidia-nvtx==13.0.85.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch) (13.0.85)
Requirement already satisfied: cuda-pathfinder>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<14,>=13.0.3->torch) (1.5.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)

In [ ]:
!pip install av
!pip install torchcodec
!pip install av torchcodec
!pip install torchvision

# 1. Install specific stable PyAV version and Torchcodec
#!pip install av==11.0.0 torchcodec datasets accelerate --upgrade

# 2. Force an update to the torchvision package if backend integration is stuck
#!pip install torchvision --upgrade --no-cache-dir

In [ ]:
#!pip install --force-reinstall torchaudio --index-url https://pytorch.org
#!pip uninstall torch torchvision torchaudio -y
#!pip install torch torchvision torchaudio --index-url https://pytorch.org

In [ ]:
from torchcodec.decoders import VideoDecoder
import sys
import torchvision.io

# Create a dummy object to satisfy the internal import check
class DummyVideoReader:
    pass

torchvision.io.VideoReader = DummyVideoReader
sys.modules['torchvision.io'].VideoReader = DummyVideoReader

running above block needed to successfully import videoDecoder in next block(avoids:- "Failed: cannot import name 'VideoReader' from 'torchvision.io' (/usr/local/lib/python3.12/dist-packages/torchvision/io/__init__.py)" error)

In [ ]:
import os
# Force torchvision to look for the PyAV backend explicitly
os.environ["TORCHVISION_VIDEO_BACKEND"] = "pyav"

import torch
import torchvision
from datasets import Dataset

# Verify the class is now safely bound into the namespace
try:
    from torchvision.io import VideoReader
    print("Success: VideoReader successfully imported!")
except ImportError as e:
    print(f"Failed: {e}")

Success: VideoReader successfully imported!

In [ ]:
import torch
print("GPU Connected:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU Name:", torch.cuda.get_device_name(0))

GPU Connected: False

In [ ]:
from torchcodec.decoders import VideoDecoder

Make sure your version of Transformers is at least 4.11.0 since the functionality was introduced in that version:

In [ ]:
import transformers

print(transformers.__version__)

5.13.1

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [ ]:
import os

print(os.getcwd())

path ="/content/gdrive/MyDrive/"
print(os.listdir(path))

/content
['analytics_vidhya', 'BERT_Model', 'Colab Notebooks', 'creditvidya_model_folder', 'Talentica_ML', 'weather_forcast', 'zenatic_ac_model_folders', 'AC_Data_hour_with_temp1.xlsx', 'AC_Data_hour_with_temp.xlsx', 'AC_Data_hour.xlsx', 'AC_Data.csv', 'hiring_assignment_cv.xlsx', 'python_intro.ipynb', 'stock_forcast_model.h5', 'test_new_6thsense.csv', 'ner_dataset.csv', 'Large_videos_pics_originaldrive', 'upsc_2026_speciesInNews.docx', 'Large_videos_part2', 'distilgpt2-finetuned-wikitext2', 'distilbert-base-uncased-finetuned-wikitext2']

You can find a script version of this notebook to fine-tune your model in a distributed fashion using multiple GPUs or TPUs [here](https://github.com/huggingface/transformers/tree/master/examples/language-modeling).

# Fine-tuning a language model

In this notebook, we'll see how to fine-tune 🤗 masked transformers based model for NLP. We'll train mode by **trainer wrapper** as well as **accelerator loop(latter for more customization)**. So what are masked models?

- **Masked language modeling**: Masked models are **class of encoder based(discriminative) model**. The model has to predict some tokens that are masked in the input(although their actual value present in labels/output set i.e. Y). It still has access to the whole sentence, so it can use the tokens before and after the tokens masked to predict their value.

## Preparing the dataset

For each of those tasks, we will use the [Wikitext 2]() dataset as an example. You can load it very easily with the 🤗 Datasets library.

In [ ]:
from datasets import load_dataset
datasets = load_dataset('Salesforce/wikitext', 'wikitext-2-raw-v1')

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

wikitext-2-raw-v1/test-00000-of-00001.pa(…): reconstructing file:   0%|          |  0.00B /  733kB

wikitext-2-raw-v1/test-00000-of-00001.pa(…): downloading bytes:           |  0.00B

wikitext-2-raw-v1/train-00000-of-00001.p(…): reconstructing file:   0%|          |  0.00B / 6.36MB

wikitext-2-raw-v1/train-00000-of-00001.p(…): downloading bytes:           |  0.00B

wikitext-2-raw-v1/validation-00000-of-00(…): reconstructing file:   0%|          |  0.00B /  657kB

wikitext-2-raw-v1/validation-00000-of-00(…): downloading bytes:           |  0.00B

Generating test split:   0%|          | 0/4358 [00:00<?, ? examples/s]

Generating train split:   0%|          | 0/36718 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/3760 [00:00<?, ? examples/s]

You can replace the dataset above with any dataset hosted on [the hub](https://huggingface.co/datasets) (🤗) or use your own files. Just uncomment the following cell and replace the paths with values that will lead to your files:

In [ ]:
# datasets = load_dataset("text", data_files={"train": path_to_train.txt, "validation": path_to_validation.txt}

You can also load datasets from a csv or a JSON file, see the [full documentation](https://huggingface.co/docs/datasets/loading_datasets.html#from-local-files) for more information.

To access an actual element, you need to select a split first, then give an index:

In [ ]:
datasets["train"][1]

{'text': ' = Valkyria Chronicles III = \n'}

In [ ]:
type(datasets), datasets.keys(), type(datasets["train"]), len(datasets["train"]), type(datasets["train"][:3]), datasets["train"][10].keys()

(datasets.dataset_dict.DatasetDict,
 dict_keys(['test', 'train', 'validation']),
 datasets.arrow_dataset.Dataset,
 36718,
 dict,
 dict_keys(['text']))

To get a sense of what the data looks like, the following function will show some examples picked randomly in the dataset.

In [ ]:
from datasets import ClassLabel
import random
import pandas as pd
from IPython.display import display, HTML

def show_random_elements(dataset, num_examples=10):
    assert num_examples <= len(dataset), "Can't pick more elements than there are in the dataset."
    picks = []
    for _ in range(num_examples):
        pick = random.randint(0, len(dataset)-1)
        while pick in picks:
            pick = random.randint(0, len(dataset)-1)
        picks.append(pick)

    df = pd.DataFrame(dataset[picks])
    for column, typ in dataset.features.items():
        if isinstance(typ, ClassLabel):
            df[column] = df[column].transform(lambda i: typ.names[i])
    display(HTML(df.to_html()))

In [ ]:
show_random_elements(datasets["train"])

As we can see, some of the texts are a full paragraph of a Wikipedia article while others are just titles or empty lines.

# **===============================================================================**

## Masked language modeling

For masked language modeling (MLM) we are going to use the same preprocessing as before for our dataset with one additional step: we will randomly mask some tokens (by replacing them by `[MASK]`) and the labels will be adjusted to only include the masked tokens (we don't have to predict the non-masked tokens).

We will use the [`distilroberta-base`](https://huggingface.co/distilroberta-base) model for this example. You can pick any of the checkpoints listed [here](https://huggingface.co/models?filter=masked-lm) instead:

In [ ]:
#model_checkpoint = "distilroberta-base"
model_checkpoint = "distilbert-base-uncased"

We can now call the tokenizer on all our texts. This is very simple, using the map method from the Datasets library. First we define a function that call the tokenizer on our texts:

We’ll also grab the word IDs if they are available, as we will need them later on to do whole word masking. We’ll wrap this in a simple function

In [ ]:
def tokenize_function(examples):
    #result = tokenizer(examples["text"], truncation=True) # beacuse of sequence lengths>512 producing index error
    result = tokenizer(examples["text"])
    if tokenizer.is_fast:
        result["word_ids"] = [result.word_ids(i) for i in range(len(result["input_ids"]))]
    return result

We can apply the same tokenization function as before(after importing tokenizer), we just need to update our tokenizer to use the checkpoint we just picked and check for pad tokens if blocks length is uneven:

In [ ]:
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained(model_checkpoint, use_fast=True)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

In [ ]:
# Check if pad_token is already assigned; if not, set it to the eos_token
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

In [ ]:
tokenized_datasets = datasets.map(tokenize_function, batched=True, num_proc=8, remove_columns=["text"])

Map (num_proc=8):   0%|          | 0/4358 [00:00<?, ? examples/s]

[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (525 > 512). Running this sequence through the model will result in indexing errors

Map (num_proc=8):   0%|          | 0/36718 [00:00<?, ? examples/s]

[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (552 > 512). Running this sequence through the model will result in indexing errors
[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (515 > 512). Running this sequence through the model will result in indexing errors
[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (844 > 512). Running this sequence through the model will result in indexing errors
[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (647 > 512). Running this sequence through the model will result in indexing errors
[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (608 > 512). Running this sequence through the model will result in indexing errors
[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (782 > 512). Running this sequence through the model will result in indexing errors
[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (592 > 512). Running this sequence through the model will result in indexing errors

Map (num_proc=8):   0%|          | 0/3760 [00:00<?, ? examples/s]

If we now look at an element of our datasets, we will see the text have been replaced by the `input_ids` the model will need:

In [ ]:
print(tokenized_datasets["train"][1])
print(type(tokenized_datasets["train"]))
tokenizer.decode(tokenized_datasets["train"][1])

{'input_ids': [101, 1027, 11748, 4801, 4360, 11906, 3523, 1027, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1], 'word_ids': [None, 0, 1, 1, 1, 2, 3, 4, None]}
<class 'datasets.arrow_dataset.Dataset'>

'[CLS] = valkyria chronicles iii = [SEP]'

We group/concat texts together and chunk them in samples of equal length `block_size`.
To do this, we will use the `map` method again, with the option `batched=True` along wit finite `batch size`(after defining **group_text** fn).

This option actually lets us change the number of examples in the datasets by returning a different number of examples than we got. This way, we can create our new samples from a batch of examples.

First, we grab the maximum length our model was pretrained with. This might be a big too big to fit in your GPU RAM, so here we take a bit less at just 128.

You can skip that step if your dataset is composed of individual sentences.

In [ ]:
# block_size = tokenizer.model_max_length
block_size = 128

In [ ]:
def group_texts(examples):
    # Concatenate all texts.
    concatenated_examples = {k: sum(examples[k], []) for k in examples.keys()}
    total_length = len(concatenated_examples[list(examples.keys())[0]])
    # We drop the small remainder, we could add padding if the model supported it instead of this drop, you can
        # customize this part to your needs.
    total_length = (total_length // block_size) * block_size
    # Split by chunks of max_len.
    result = {
        k: [t[i : i + block_size] for i in range(0, total_length, block_size)]
        for k, t in concatenated_examples.items()
    }
    result["labels"] = result["input_ids"].copy()
    return result

In [ ]:
lm_datasets = tokenized_datasets.map(
    group_texts,
    batched=True,
    batch_size=1000,# deafualt batch_szie also 1000
    num_proc=8,
)# here batch inside map only facilitates faster processing, does not group final data in batches like pytorch dataloader(so keep batch size =32, 64 in dataloader)

Map (num_proc=8):   0%|          | 0/4358 [00:00<?, ? examples/s]

Map (num_proc=8):   0%|          | 0/36718 [00:00<?, ? examples/s]

Map (num_proc=8):   0%|          | 0/3760 [00:00<?, ? examples/s]

In [ ]:
print(type(lm_datasets["train"]), type(lm_datasets["validation"]))
print(len(lm_datasets["train"]), len(lm_datasets["validation"]), len(lm_datasets["test"]))

<class 'datasets.arrow_dataset.Dataset'> <class 'datasets.arrow_dataset.Dataset'>
18551 1918 2198

And we can check our datasets have changed: now the samples contain chunks of `block_size` contiguous tokens, potentially spanning over several of our original texts. Also Input ids = labels

In [ ]:
print(tokenizer.decode(lm_datasets["train"][1]["input_ids"]))
if(tokenizer.decode(lm_datasets["train"][1]["input_ids"]) == tokenizer.decode(lm_datasets["train"][1]["labels"])):
  print("Same")

the first game and follows the " nameless ", a penal military unit serving the nation of gallia during the second europan war who perform secret black operations and are pitted against the imperial unit " calamaty raven ". [SEP] [CLS] the game began development in 2010, carrying over a large portion of the work done on valkyria chronicles ii. while it retained the standard features of the series, it also underwent multiple adjustments, such as making the game more forgiving for series newcomers. character designer raita honjou and composer hitoshi sakimoto both returned from previous entries, along with valkyria chronicles ii director takeshi
Same

In [ ]:
#from pprint import pprint
for iter in range(5):
  elm_inputid = lm_datasets["train"][iter]["input_ids"]
  if(-100 not in elm_inputid):
    print(elm_inputid)
    print("Padded", len(elm_inputid))

  print("~"*100)
  elm_mask =lm_datasets["train"][iter]["attention_mask"]
  if(0 not in elm_mask):
    print(elm_mask)
    print("complete_masked", len(elm_mask))
  print("-"*270)

[101, 102, 101, 1027, 11748, 4801, 4360, 11906, 3523, 1027, 102, 101, 102, 101, 12411, 5558, 2053, 11748, 4801, 4360, 1017, 1024, 4895, 2890, 27108, 5732, 11906, 1006, 2887, 1024, 1856, 1806, 1671, 30222, 30218, 30259, 30227, 30255, 30258, 30219, 2509, 1010, 5507, 1012, 11748, 4801, 4360, 1997, 1996, 11686, 1017, 1007, 1010, 4141, 3615, 2000, 2004, 11748, 4801, 4360, 11906, 3523, 2648, 2900, 1010, 2003, 1037, 8608, 2535, 1030, 1011, 1030, 2652, 2678, 2208, 2764, 2011, 16562, 1998, 2865, 1012, 4432, 2005, 1996, 9160, 12109, 1012, 2207, 1999, 2254, 2249, 1999, 2900, 1010, 2009, 2003, 1996, 2353, 2208, 1999, 1996, 11748, 4801, 4360, 2186, 1012, 15440, 1996, 2168, 10077, 1997, 8608, 1998, 2613, 1030, 1011, 1030, 2051, 11247, 2004, 2049, 16372, 1010, 1996, 2466, 3216, 5903, 2000]
Padded 128
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
complete_masked 128
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[1996, 2034, 2208, 1998, 4076, 1996, 1000, 2171, 3238, 1000, 1010, 1037, 18476, 2510, 3131, 3529, 1996, 3842, 1997, 26033, 2401, 2076, 1996, 2117, 12124, 2078, 2162, 2040, 4685, 3595, 2304, 3136, 1998, 2024, 25895, 2114, 1996, 4461, 3131, 1000, 10250, 8067, 3723, 10000, 1000, 1012, 102, 101, 1996, 2208, 2211, 2458, 1999, 2230, 1010, 4755, 2058, 1037, 2312, 4664, 1997, 1996, 2147, 2589, 2006, 11748, 4801, 4360, 11906, 2462, 1012, 2096, 2009, 6025, 1996, 3115, 2838, 1997, 1996, 2186, 1010, 2009, 2036, 9601, 3674, 24081, 1010, 2107, 2004, 2437, 1996, 2208, 2062, 2005, 23795, 2005, 2186, 24159, 1012, 2839, 5859, 15547, 2696, 10189, 23099, 1998, 4543, 2718, 24303, 7842, 21138, 11439, 2119, 2513, 2013, 3025, 10445, 1010, 2247, 2007, 11748, 4801, 4360, 11906, 2462, 2472, 3138, 4048]
Padded 128
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
complete_masked 128
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[11472, 10830, 1012, 1037, 2312, 2136, 1997, 4898, 8971, 1996, 5896, 1012, 1996, 2208, 1005, 1055, 3098, 4323, 2001, 7042, 2011, 2089, 1005, 1050, 1012, 102, 101, 2009, 2777, 2007, 3893, 4341, 1999, 2900, 1010, 1998, 2001, 5868, 2011, 2119, 2887, 1998, 2530, 4401, 1012, 2044, 2713, 1010, 2009, 2363, 26720, 4180, 1010, 2247, 2007, 2019, 4423, 3179, 1999, 2281, 1997, 2008, 2095, 1012, 2009, 2001, 2036, 5967, 2046, 8952, 1998, 2019, 2434, 2678, 7284, 2186, 1012, 2349, 2000, 2659, 4341, 1997, 11748, 4801, 4360, 11906, 2462, 1010, 11748, 4801, 4360, 11906, 3523, 2001, 2025, 22574, 1010, 2021, 1037, 5470, 5449, 11892, 2007, 1996, 2208, 1005, 1055, 4423, 3179, 2001, 2207, 1999, 2297, 1012, 2865, 1012, 4432, 2052, 2709, 2000, 1996, 6329, 2007, 1996, 2458, 1997, 11748, 4801]
Padded 128
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
complete_masked 128
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[4360, 1024, 24296, 4329, 2005, 1996, 9160, 1018, 1012, 102, 101, 102, 101, 1027, 1027, 11247, 1027, 1027, 102, 101, 102, 101, 2004, 2007, 3025, 11748, 4801, 7895, 11906, 2399, 1010, 11748, 4801, 4360, 11906, 3523, 2003, 1037, 8608, 2535, 1030, 1011, 1030, 2652, 2208, 2073, 2867, 2202, 2491, 1997, 1037, 2510, 3131, 1998, 2202, 2112, 1999, 6416, 2114, 4099, 2749, 1012, 3441, 2024, 2409, 2083, 5021, 2338, 1030, 1011, 1030, 2066, 9320, 2007, 6579, 2839, 9668, 1010, 2007, 3494, 4092, 6822, 2083, 6126, 4613, 17255, 1998, 6822, 2083, 4895, 6767, 6610, 2094, 3793, 1012, 1996, 2447, 22901, 2083, 1037, 2186, 1997, 7399, 6416, 1010, 6360, 14058, 2004, 7341, 2008, 2064, 2022, 10350, 11728, 2083, 1998, 15712, 2098, 2004, 2027, 2024, 14058, 1012, 1996, 2799, 2000, 2169, 2466]
Padded 128
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
complete_masked 128
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[3295, 2006, 1996, 4949, 9783, 5834, 2006, 2019, 3265, 2447, 1005, 1055, 3921, 1024, 2043, 2028, 5724, 2003, 3479, 1010, 1996, 2060, 2003, 10203, 2125, 2000, 1996, 2447, 1012, 2648, 6416, 1010, 1996, 2447, 3494, 2717, 1999, 1037, 3409, 1010, 2073, 3197, 2064, 2022, 28749, 1998, 2839, 3930, 5158, 1012, 4077, 1996, 2364, 2466, 6416, 2024, 2839, 1030, 1011, 1030, 3563, 4942, 6416, 8800, 2000, 2367, 4686, 2372, 1012, 2044, 1996, 2208, 1005, 1055, 6503, 1010, 3176, 4178, 2024, 14058, 1010, 2070, 1997, 2068, 2383, 1037, 3020, 7669, 2084, 2216, 2179, 1999, 1996, 2717, 1997, 1996, 2208, 1012, 2045, 2024, 2036, 2293, 12504, 3787, 3141, 2000, 1996, 2208, 1005, 1055, 2048, 2364, 18869, 2015, 1010, 2348, 2027, 2202, 1037, 2200, 3576, 2535, 1012, 102, 101, 1996, 2208, 1005]
Padded 128
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
complete_masked 128
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

In [ ]:
lm_datasets.keys(), lm_datasets["train"][1].keys()

(dict_keys(['test', 'train', 'validation']),
 dict_keys(['input_ids', 'token_type_ids', 'attention_mask', 'word_ids', 'labels']))

The rest is very similar to what we had, with two exceptions. First we use a model suitable for masked LM:

In [ ]:
from transformers import AutoModelForMaskedLM
model = AutoModelForMaskedLM.from_pretrained(model_checkpoint)

model.safetensors: reconstructing file:   0%|          |  0.00B /  268MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch(when loading **distilroberta**). But this error not there when using **distilbert** in above block

# Training approaches:-(1)using .trainer() method, (2) accelerator loop

**Loss Selection**
Choose Internal Model Loss (AutoCausalLM / Forward Pass Loss): Let the AutoModelForCausalLM compute the cross-entropy loss internally by passing labels=input_ids (shifted internally by the model).

**Why:** Computing loss inside the model ensures proper handling of shifted next-token prediction targets and keeps mixed-precision scaling stable under Accelerate. Manual cross-entropy calculation outside the model requires flattening logits and shifting tokens manually, risking shape mismatch errors or full-precision bottlenecks.

We redefine our `TrainingArguments`:

*1)Trainer method*

In [ ]:
from transformers import Trainer, TrainingArguments

Like before, the last argument to setup everything so we can push the model to the [Hub](https://huggingface.co/models) regularly during training. Remove it if you didn't follow the installation steps at the top of the notebook. If you want to save your model locally in a name that is different than the name of the repository it will be pushed, or if you want to push your model under an organization and not your name space, use the `hub_model_id` argument to set the repo name (it needs to be the full name, including your namespace: for instance `"sgugger/bert-finetuned-wikitext2"` or `"huggingface/bert-finetuned-wikitext2"`).

Finally, we use a special `data_collator`. The `data_collator` is a function that is responsible of taking the samples and batching them in tensors. In the previous example, we had nothing special to do, so we just used the default for this argument. Here we want to do the random-masking. We could do it as a pre-processing step (like the tokenization) but then the tokens would always be masked the same way at each epoch. By doing this step inside the `data_collator`, we ensure this random masking is done in a new way each time we go over the data.

To do this masking for us, the library provides a `DataCollatorForLanguageModeling`. We can adjust the probability of the masking:

In [ ]:
from transformers import DataCollatorForLanguageModeling
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm_probability=0.15)

To see how the random masking works, let’s feed a few examples to the data collator. Since it expects a list of dicts, where each dict represents a single chunk of contiguous text, we first iterate over the dataset before feeding the batch to the collator. We remove the "word_ids" key for this data collator as it does not expect it:

In [ ]:
samples = [lm_datasets["train"][i] for i in range(2)]
for sample in samples:
    _ = sample.pop("word_ids")

for chunk in data_collator(samples)["input_ids"]:
    print(f"\n'>>> {tokenizer.decode(chunk)}'")

'>>> [CLS] [SEP] [CLS] = [MASK]kyria chronicles iii = [SEP] [CLS] [SEP] [CLS] senjo no valkyria 3 : unre [MASK]ded chronicles ( japanese : 戦 場 のウァルnumュリア3 [MASK] lit. [MASK] [MASK]ria of the battlefield 3 ), commonly referred [MASK] as valkyria chronicles iii outside japan, is a tactical role [MASK] - @ playing video [MASK] developed by sega and [MASK]. vision for the playstation portable. released in january [MASK] in [MASK], it is [MASK] third game in the val [MASK]ria series. [MASK] the same fusion of tactical and real @ - @ time gameplay as its predecessors, the story runs parallel to'

'>>> the first game and [MASK] the " nameless [MASK], a [MASK] military unit serving the nation of gallia [MASK] [MASK] second europa [MASK] war who perform secret black operations and are [MASK] against the imperial unit [MASK] [MASK]amaty [MASK] ". [SEP] [CLS] the game began development in 2010 [MASK] carrying over a highlighted portion [MASK] the work done on valkyria chronicles ii. while it retained the [MASK] features of the series, it also underwent [MASK] adjustments, such ios making the game more forgiving for series newcomers. [MASK] designer raita honjou and composer hitoshi sa [MASK]oto both returned from previous entries, along with val [MASK]ria chronicles [MASK] director takeshi'

concept of **whole_word_masking_data_collator** to be checked later in this colab

Our data already segregated in train, validation, test; else we can use follwoing code for train:test split(presently commented)

In [ ]:
"""
train_size = 10_000(size)
test_size = int(0.1 * train_size)

downsampled_dataset = lm_datasets["train"].train_test_split(
    train_size=train_size, test_size=test_size, seed=42
)
downsampled_dataset
"""

'\ntrain_size = 10_000(size)\ntest_size = int(0.1 * train_size)\n\ndownsampled_dataset = lm_datasets["train"].train_test_split(\n    train_size=train_size, test_size=test_size, seed=42\n)\ndownsampled_dataset\n'

And some `TrainingArguments`:

# here we use train and evaluation via batch with logs in every batch iter(something missed in fine-tuning causal model via trainer earlier)

In [ ]:
batch_size = 32
# Show the training loss with every epoch
logging_steps = len(lm_datasets["train"]) // batch_size
model_name = model_checkpoint.split("/")[-1]

training_args = TrainingArguments(
    output_dir= "./local_checkpoints"+f"{model_name}-finetuned-wikitext2",#avoid giving mounted drive path as models
    #will consumeheavy write operations that quickly max out your Drive storage and API limits
    eval_strategy = "epoch",
    learning_rate=2e-5,
    weight_decay=0.01,
    push_to_hub=False,
    fp16=True,
    save_strategy="epoch",
    #save_steps=1000,          # Don't save too frequently, but to be used when both eval strategy and save strategy are "steps"
    save_total_limit=1,      # Automatically deletes older checkpoints; keeps only the newest
    load_best_model_at_end=True, # Keeps your optimal weights

    per_device_train_batch_size=batch_size,# batch_wise train like in acclerator loop (not in causal model finetuning trainer method)
    per_device_eval_batch_size=batch_size,# batch_wise evaluation like in acclerator loop (not in causal model finetuning trainer method)
    logging_steps=logging_steps,# to show logs with each bactch iter(not in causal model finetuning trainer method)
)

Then we just have to pass everything to `Trainer` and begin training:

In [ ]:
'''
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=lm_datasets["train"],
    eval_dataset=lm_datasets["validation"],
    data_collator=data_collator,
)
'''

'\ntrainer = Trainer(\n    model=model,\n    args=training_args,\n    train_dataset=lm_datasets["train"],\n    eval_dataset=lm_datasets["validation"],\n    data_collator=data_collator,\n)\n'

In [ ]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=lm_datasets["train"],
    eval_dataset=lm_datasets["validation"],
    data_collator= data_collator,
    processing_class= tokenizer,#The "tokenizer" argument in Hugging Face Trainer is deprecated, and processing_class is its modern replacement.
    #tokenizer = tokenizer,
)

In [ ]:
trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[transformers] There were missing keys in the checkpoint model loaded: ['vocab_projector.weight'].

TrainOutput(global_step=1740, training_loss=2.1247746363453484, metrics={'train_runtime': 324.6466, 'train_samples_per_second': 171.426, 'train_steps_per_second': 5.36, 'total_flos': 1844356505052672.0, 'train_loss': 2.1247746363453484, 'epoch': 3.0})

Like before, we can evaluate our model on the validation set. The perplexity is much lower than for the CLM objective because for the MLM objective, we only have to make predictions for the masked tokens (which represent 15% of the total here) while having access to the rest of the tokens. It's thus an easier task for the model.

In [ ]:
import math
eval_results = trainer.evaluate()
print(f"Perplexity: {math.exp(eval_results['eval_loss']):.2f}")

Perplexity: 7.21

2)Using accelerator loop

In [ ]:
#import torch
#import torchvision
from torch.utils.data import DataLoader
from transformers import AutoModelForCausalLM, AutoTokenizer, default_data_collator
from accelerate import Accelerator,DataLoaderConfiguration
from torch.optim import AdamW
from datasets import load_dataset

In [ ]:
from transformers import DataCollatorForLanguageModeling
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm_probability=0.15)

**DataCollatorForLanguageModeling also applies random masking with each evaluation**, so we’ll see some fluctuations in our perplexity scores with each training run. One way to eliminate this source of randomness is to apply the masking once on the whole test set, and then use the default data collator in 🤗 Transformers to collect the batches during evaluation. To see how this works, let’s implement a simple function that applies the masking on a batch, similar to our first encounter with DataCollatorForLanguageModeling:

In [ ]:
def insert_random_mask(batch):
    features = [dict(zip(batch, t)) for t in zip(*batch.values())]
    masked_inputs = data_collator(features)
    # Create a new "masked" column for each column in the dataset
    return {"masked_" + k: v.numpy() for k, v in masked_inputs.items()}

Next, we’ll apply this function to our test set and drop the **unmasked columns so we can replace them with the masked ones**. You can use whole word masking by replacing the data_collator above with the appropriate one, in which case you should remove the first line here:

In [ ]:
lm_datasets = lm_datasets.remove_columns(["word_ids"])

eval_dataset = lm_datasets["validation"].map(
    insert_random_mask,
    batched=True,
    remove_columns=lm_datasets["validation"].column_names,
)
eval_dataset = eval_dataset.rename_columns(
    {
        "masked_input_ids": "input_ids",
        "masked_token_type_ids": "token_type_ids",
        "masked_attention_mask": "attention_mask",
        "masked_labels": "labels",
    }
)

test_dataset = lm_datasets["test"].map(
    insert_random_mask,
    batched=True,
    remove_columns=lm_datasets["test"].column_names,
)
test_dataset = test_dataset.rename_columns(
    {
        "masked_input_ids": "input_ids",
        "masked_token_type_ids": "token_type_ids",
        "masked_attention_mask": "attention_mask",
        "masked_labels": "labels",
    }
)

Map:   0%|          | 0/1918 [00:00<?, ? examples/s]

Map:   0%|          | 0/2198 [00:00<?, ? examples/s]

In [ ]:
#from torch.utils.data import DataLoader
#from transformers import default_data_collator

batch_size = 32
train_dataloader = DataLoader(
    lm_datasets["train"],
    shuffle=True,
    batch_size=batch_size,
    collate_fn=data_collator,
)

In [ ]:
eval_dataloader = DataLoader(
    eval_dataset, batch_size=batch_size, collate_fn=default_data_collator
)# by default shuffle is false


test_dataloader = DataLoader(
    test_dataset, batch_size=batch_size, collate_fn=default_data_collator
)# by default shuffle is false

In [ ]:
print(len(lm_datasets["train"]), len(train_dataloader))
print(len(eval_dataset), len(eval_dataloader))
print(len(test_dataset), len(test_dataloader))

print(type(train_dataloader), type(lm_datasets["train"]))

18551 580
1918 60
2198 69
<class 'accelerate.data_loader.DataLoaderShard'> <class 'datasets.arrow_dataset.Dataset'>

In [ ]:
test_dataloader.keys()

AttributeError: 'StatefulDataLoader' object has no attribute 'keys'

In [ ]:
test_dataloader[0]

TypeError: 'DataLoaderShard' object is not subscriptable

In [ ]:
optimizer = AdamW(
    model.parameters(),
    lr=3e-5,
    eps=1e-8,
)

In [ ]:
'''
accelerator = Accelerator()
model, optimizer, train_dataloader, eval_dataloader = accelerator.prepare(
    model, optimizer, train_dataloader, eval_dataloader
)
'''
# 1. Enable stateful dataloader configuration if tracking iteration states
dataloader_config = DataLoaderConfiguration(use_stateful_dataloader=True)
accelerator = Accelerator(dataloader_config=dataloader_config)

# 5. Prepare everything with Accelerator (crucial for distributed setups)
model, optimizer, train_dataloader, eval_dataloader, test_dataloader = accelerator.prepare(
    model, optimizer, train_dataloader, eval_dataloader, test_dataloader)

In [ ]:

from transformers import get_linear_schedule_with_warmup

num_train_epochs = 3
#max_grad_norm = 1.0

# Total number of training steps is number of batches * number of epochs.
total_steps = len(train_dataloader) * num_train_epochs

# Create the learning rate scheduler.
scheduler = get_linear_schedule_with_warmup(
    optimizer,
    num_warmup_steps=0,
    num_training_steps=total_steps
)

In [ ]:
from tqdm.auto import tqdm
import torch
import math

progress_bar = tqdm(range(total_steps))

train_loss_values, eval_loss_values = [], []

for epoch in range(num_train_epochs):
    # Put the model into training mode.
    model.train()

    # Reset the total loss for this epoch.
    total_loss = 0

    for batch in train_dataloader:
        outputs = model(**batch)

        # get the loss
        loss = outputs.loss

        # Perform a backward pass to calculate the gradients
        accelerator.backward(loss)

        # track train loss
        total_loss+= loss.item()
        optimizer.step()
        scheduler.step()
        optimizer.zero_grad()
        progress_bar.update(1)

    # Calculate the average loss over the training data.
    avg_train_loss = total_loss / len(train_dataloader)
    print(f">>> Epoch {epoch}: avg_Training/train Loss: {avg_train_loss}")

    # Store the loss value for plotting the learning curve.
    train_loss_values.append(avg_train_loss)

    # Evaluation
    model.eval()
    losses = []
    for step, batch in enumerate(eval_dataloader):
        with torch.no_grad():
            outputs = model(**batch)

        loss = outputs.loss
        losses.append(accelerator.gather(loss.repeat(batch_size)))

    losses = torch.cat(losses)
    losses = losses[: len(eval_dataloader)]

    eval_loss = losses.mean().item()
    print(f">>> Epoch {epoch}: avg_Validation/eval Loss: {eval_loss}")

    # Store the loss value for plotting the learning curve.
    eval_loss_values.append(losses.mean().item())

    try:
        perplexity = math.exp(torch.mean(losses))
    except OverflowError:
        perplexity = float("inf")

    print(f">>> Epoch {epoch}: Perplexity: {perplexity}")

  0%|          | 0/1740 [00:00<?, ?it/s]

>>> Epoch 0: avg_Training/train Loss: 2.0317559289521183
>>> Epoch 0: avg_Validation/eval Loss: 1.6698743104934692
>>> Epoch 0: Perplexity: 5.311500155390793
>>> Epoch 1: avg_Training/train Loss: 1.9797649950816714
>>> Epoch 1: avg_Validation/eval Loss: 1.6396726369857788
>>> Epoch 1: Perplexity: 5.153482176605042
>>> Epoch 2: avg_Training/train Loss: 1.9443689040068923
>>> Epoch 2: avg_Validation/eval Loss: 1.632906198501587
>>> Epoch 2: Perplexity: 5.118729166127649

In [ ]:
model.eval()
losses = []
for step, batch in enumerate(eval_dataloader):
    with torch.no_grad():
        outputs = model(**batch)

    loss = outputs.loss
    losses.append(accelerator.gather(loss.repeat(batch_size)))

losses = torch.cat(losses)
losses = losses[: len(eval_dataloader)]

eval_loss = losses.mean().item()
print(f">>> Epoch {epoch}: avg_Validation/eval Loss: {eval_loss}")

# Store the loss value for plotting the learning curve.
eval_loss_values.append(losses.mean().item())

try:
    perplexity = math.exp(torch.mean(losses))
except OverflowError:
    perplexity = float("inf")

print(f">>> Epoch {epoch}: Perplexity: {perplexity}")

>>> Epoch 2: avg_Validation/eval Loss: 1.632906198501587
>>> Epoch 2: Perplexity: 5.118729166127649

# Use save method of whichever approach gives lower perplexity

**Save by Trainer method**

You can now upload the result of the training to the Hub, just execute this instruction:

In [ ]:
#trainer.push_to_hub()

In [ ]:
trainer.save_model(path+ f"{model_name}-finetuned-wikitext2")# also saves training_args.bin(not saved in accelerator method below)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

**save by acclereate loop method**

Your test data loader's batch size or length is **becoming zero from batch_size(32 here) because** ❎


*   Hugging Face Accelerate wrapper or distributed sampler splits or exhausts the
dataset across processes
*   or an active dynamic batch-size finder/callback scaled it down to zero

*   or the remaining data samples did not divide evenly into the number of active GPU

To fix these:-
1) re-initialize the dataloader(if possible)
2) retrieve original batch size instead of querying it from dynamic object(here dataloader)
3)or the remaining data samples did not divide evenly into the number of active GPU

2nd most practical

In [ ]:
print(test_dataloader.batch_size)
print(test_dataloader.collate_fn)
print(test_dataloader.num_workers)
print(test_dataloader.pin_memory)

print("*"*50)
print(train_dataloader.batch_size)
print(train_dataloader.collate_fn)
print(train_dataloader.num_workers)
print(train_dataloader.pin_memory)

print("*"*50)

print(eval_dataloader.batch_size)
print(eval_dataloader.collate_fn)
print(eval_dataloader.num_workers)
print(eval_dataloader.pin_memory)

None
<function default_data_collator at 0x7fd317e094e0>
0
False
**************************************************
None
DataCollatorForLanguageModeling(tokenizer=BertTokenizer(name_or_path='distilbert-base-uncased', vocab_size=30522, model_max_length=512, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	100: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	101: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	102: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	103: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
}), mlm=True, whole_word_mask=False, mlm_probability=0.15, mask_replace_prob=0.8, random_replace_prob=0.1, pad_to_multiple_of=None, return_tensors='pt', seed=None)
0
False
**************************************************
None
<function default_data_collator at 0x7fd317e094e0>
0
False

In [ ]:
# 1. Wait for all processes to finish training(Ensures no hanging or broken shards across multi-GPU setups)
accelerator.wait_for_everyone()# Synchronize processes before saving

# 2. Unwrap the model to strip away the distributed training shell
unwrapped_model = accelerator.unwrap_model(model)#Unwrap Model: accelerator.unwrap_model(model) removes the extra layers added by
#accelerator.prepare() so you get your raw base model back.

# 3. Save only on the main process to avoid file conflicts
if accelerator.is_main_process:
    # This creates the weights and the required config.json file

    model_name = model_checkpoint.split("/")[-1]
    unwrapped_model.save_pretrained(path+ f"{model_name}-finetuned-wikitext2", save_function=accelerator.save)#Save Function: save_function=accelerator.save makes
    #sure the model saves correctly across multiple GPUs or machines without breaking
    tokenizer.save_pretrained(path+ f"{model_name}-finetuned-wikitext2")

    # Save the test dataloader setup
    # Because DataLoaders are runtime iterators, we save the underlying dataset indices/tensors(here its test_dataset)
    dataloader_state = {
        #"dataset_dict": tokenized_datasets["test"].to_dict(), # Converts Apache Arrow table data to a dict
        #"dataset_dict": lm_datasets["test"].to_dict(),
        "dataset_dict": test_dataset.to_dict(),
        #"batch_size": test_dataloader.batch_size,#refer comment on 2nd last block
        "batch_size": batch_size,
        "collate_fn": test_dataloader.collate_fn,

        "num_workers": test_dataloader.num_workers,
        "pin_memory": test_dataloader.pin_memory,
    }
    accelerator.save(dataloader_state, os.path.join(path+ f"{model_name}-finetuned-wikitext2", "test_dataloader_state.pt"))
    print(f"Model and evaluation states successfully saved to {path+ f"{model_name}-finetuned-wikitext2"}")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model and evaluation states successfully saved to /content/gdrive/MyDrive/distilbert-base-uncased-finetuned-wikitext2

# Load saved model for inference

You can now share this model with all your friends, family, favorite pets: they can all load it with the identifier `"your-username/the-name-you-picked"` so for instance:

```python
from transformers import AutoModelForMaskedLM

model = AutoModelForMaskedLM.from_pretrained("sgugger/my-awesome-model")
```

In [ ]:
import torch
from torch.utils.data import DataLoader
from transformers import AutoTokenizer, AutoModelForMaskedLM
from datasets import Dataset
from accelerate import Accelerator, DataLoaderConfiguration
import os

In [ ]:
#from transformers import AutoTokenizer, AutoModelForMaskedLM

path ="/content/gdrive/MyDrive/"

#model_checkpoint = "distilroberta-base"
model_checkpoint = "distilbert-base-uncased"

model_name = model_checkpoint.split("/")[-1]

# 1. Enable stateful dataloader configuration if tracking iteration states(states of dataloader)
dataloader_config = DataLoaderConfiguration(use_stateful_dataloader=True)
accelerator = Accelerator(dataloader_config=dataloader_config)

# 1. Reconstruct the saved Model and Tokenizer
tokenizer_infer =AutoTokenizer.from_pretrained(path+ f"{model_name}-finetuned-wikitext2", use_fast=True)
model_infer = AutoModelForMaskedLM.from_pretrained(path+ f"{model_name}-finetuned-wikitext2")

# 2. Reconstruct the saved Test DataLoader
dataloader_file = os.path.join(path+ f"{model_name}-finetuned-wikitext2", "test_dataloader_state.pt")
if not os.path.exists(dataloader_file):
    raise FileNotFoundError("Saved test dataloader state was not found.")

#saved_state = torch.load(dataloader_file, map_location="cpu")# unpicklig error: This error happens because PyTorch restricted its default file-loading settings to block non-weight data structures from executing untrusted code.
saved_state = torch.load(dataloader_file, map_location="cpu", weights_only=False)#fast fix of above error

# Rebuild the HF Dataset object from the saved dict
reconstructed_dataset = Dataset.from_dict(saved_state["dataset_dict"])
reconstructed_dataset.set_format("torch", columns=["input_ids", "token_type_ids", "attention_mask", "labels"])

# Rebuild the standard PyTorch Dataloader
test_dataloader = DataLoader(
    reconstructed_dataset,
    batch_size=saved_state["batch_size"],
    collate_fn=saved_state["collate_fn"],
    num_workers=saved_state["num_workers"],
    pin_memory=saved_state["pin_memory"],
    shuffle=False
)

# 3. Prepare components for the inference accelerator device context
model_infer, test_dataloader = accelerator.prepare(model_infer, test_dataloader)

# 4. Perform Inference Loop
model_infer.eval()

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

DistilBertForMaskedLM(
  (activation): GELUActivation()
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSelfAttention(
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (vocab_transform): Linear(in_features=768, out_features=768, bias=True)
  (vocab_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
  (vocab_projector): Linear(in_features=768, out_features=30522, bias=True)
  (mlm_loss_fct): CrossEntropyLoss()
)

In [ ]:
# Check if pad_token is already assigned; if not, set it to the eos_token
if tokenizer_infer.pad_token is None:
    tokenizer_infer.pad_token = tokenizer.eos_token

**Inference on test sentences**

1)Frozen Randoming masking in batch of test sentences

In [ ]:
len(test_dataloader)

69

Previously to avoid **DataCollatorForLanguageModeling also applies random masking with each evaluation and test**:-

1.) eliminate this source of randomness is to apply the **masking once on the whole test set, and then use the default data collator in 🤗 Transformers to collect the batches during evaluation**(validation set during training and test set in inference after loading the saved fine tuned model).

2.) Save the prepared test dataloader mapped with particular permutation state of mask_id assignment by **DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm_probability=0.15)** during **initial creation of train, validation and test dataloader during training loop setup**

In [ ]:
model_infer.eval()
torch.manual_seed(42)

from tqdm import tqdm
losses =[]


for step, batch in tqdm(enumerate(test_dataloader)):
  with torch.no_grad():
      outputs = model_infer(**batch)

  loss = outputs.loss
  losses.append(accelerator.gather(loss.repeat(batch_size)))


losses = torch.cat(losses)
print(losses)
losses = losses[: len(test_dataloader)]

test_loss = losses.mean().item()
print(f">>> Saved model: avg_test Loss: {test_loss}")

try:
    perplexity = math.exp(torch.mean(losses))
except OverflowError:
    perplexity = float("inf")

print(f">>> Saved model: Perplexity: {perplexity}")

69it [00:10,  6.32it/s]

tensor([1.8454, 1.8454, 1.8454,  ..., 2.2279, 2.2279, 2.2279], device='cuda:0')
>>> Saved model: avg_test Loss: 1.9583160877227783
>>> Saved model: Perplexity: 7.0873824807901995

In [ ]:
for batch in test_dataloader:

  print(type(batch))
  del batch["labels"]
  features = [dict(zip(batch, t)) for t in zip(*batch.values())]#convert dict of list blocks into list of indvl dict having values as indvl chunks for
  #corresponding keys

  #print(features)

  for block in features[:3]:

    for key in block.keys():
      block[key] =block[key].reshape(1, block_size)

    print(tokenizer_infer.decode(block["input_ids"]))

    #block =block.convert_to_tensors(tensor_type="pt")

    token_logits = model_infer(**block).logits #indivl inp_ids_pred_start

    # Find where the mask tokens are located
    mask_token_indices = torch.where(
        block["input_ids"] == tokenizer_infer.mask_token_id
    )[1]

    # Extract predictions for each mask index
    for idx in mask_token_indices:
      mask_logits = token_logits[0, idx, :]
      top_tokens = torch.topk(mask_logits, k=1, dim=-1).indices

      decoded_words = [tokenizer_infer.decode([token]) for token in top_tokens]

      block["input_ids"][0][idx] = top_tokens[0]#replace mask token_ids with topmost predicted ids for each masked index

      print(f"Predictions for mask at index {idx.item()}: {decoded_words}") #indivl inp_ids_pred_ends

    print(tokenizer_infer.decode(block["input_ids"]))# aggregate sentence with all topmost predicted tokens replaces
    print("*"*700)
  break

<class 'dict'>
['[CLS] [SEP] [CLS] = robert boult [MASK] = [SEP] [CLS] [SEP] [CLS] robert [MASK]ulter is an english film, television [MASK] theatre actor [MASK] he had a guest @ - @ starring role on the television series the bill in 2000. this was followed by a starring role in the play herons written by simon stephens, which [MASK] performed in 2001 at the royal court theatre. [MASK] had [MASK] guest [MASK] in the television [MASK] judge john deed in 2002. in 2004 boult [MASK] landed a role as " craig " in the episode " teddy \' s story " [MASK] habitat television [MASK] the long firm ; [MASK] starred alongside actors mark strong and derek jacobi [MASK]']
Predictions for mask at index 7: ['##er']
Predictions for mask at index 14: ['bo']
Predictions for mask at index 23: ['and']
Predictions for mask at index 26: ['.']
Predictions for mask at index 63: ['was']
Predictions for mask at index 73: ['he']
Predictions for mask at index 75: ['a']
Predictions for mask at index 77: ['appearance']
Predictions for mask at index 81: ['series']
Predictions for mask at index 92: ['##er']
Predictions for mask at index 109: ['on']
Predictions for mask at index 112: ['series']
Predictions for mask at index 117: ['he']
Predictions for mask at index 127: ['.']
['[CLS] [SEP] [CLS] = robert boulter = [SEP] [CLS] [SEP] [CLS] robert boulter is an english film, television and theatre actor. he had a guest @ - @ starring role on the television series the bill in 2000. this was followed by a starring role in the play herons written by simon stephens, which was performed in 2001 at the royal court theatre. he had a guest appearance in the television series judge john deed in 2002. in 2004 boulter landed a role as " craig " in the episode " teddy \' s story " on habitat television series the long firm ; he starred alongside actors mark strong and derek jacobi.']
****************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
['he was cast in the 2005 theatre productions [MASK] the philip ridley play mercury fur, which was performed at the drum theatre in plymouth [MASK] the menier chocolate [MASK] [MASK] london. [MASK] was directed by john tiffany [MASK] starred alongside ben whishaw, shane [MASK]za, harry kent [MASK] fraser ayres, sophie stanton and dominic hall. [SEP] [CLS] in 2006, boulter starred [MASK] [MASK]hishaw in the play citizenship written by mark raven [MASK]. he [MASK] on a 2006 episode of the television series, doctors, [MASK] by a role in the 2007 theatre production of how to curse directed by josie rourke. how to [MASK] was performed [MASK] [MASK] theatre']
Predictions for mask at index 8: ['of']
Predictions for mask at index 25: ['and']
Predictions for mask at index 30: ['factory']
Predictions for mask at index 31: ['in']
Predictions for mask at index 34: ['it']
Predictions for mask at index 40: ['and']
Predictions for mask at index 49: ['lan']
Predictions for mask at index 54: [',']
Predictions for mask at index 75: ['alongside']
Predictions for mask at index 76: ['w']
Predictions for mask at index 87: ['##hill']
Predictions for mask at index 90: ['appeared']
Predictions for mask at index 102: ['followed']
Predictions for mask at index 122: ['curse']
Predictions for mask at index 125: ['at']
Predictions for mask at index 126: ['the']
['he was cast in the 2005 theatre productions of the philip ridley play mercury fur, which was performed at the drum theatre in plymouth and the menier chocolate factory in london. it was directed by john tiffany and starred alongside ben whishaw, shane lanza, harry kent, fraser ayres, sophie stanton and dominic hall. [SEP] [CLS] in 2006, boulter starred alongside whishaw in the play citizenship written by mark ravenhill. he appeared on a 2006 episode of the television series, doctors, followed by a role in the 2007 theatre production of how to curse directed by josie rourke. how to curse was performed at the theatre']
****************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
['in the london signed of hammersmith and fulham. boulter starred in two films in 2008, daylight robbery by filmmaker paris leonti, and donkey punch directed by [MASK]ly blackburn. in may 2008 [MASK] [MASK] [MASK]er made a guest appearance on a two [MASK] - [MASK] part episode arc of [MASK] television series waking the dead, [MASK] by an appearance on swamps television series [MASK] in schooling 2008. he had [MASK] recurring role in ten [MASK] of the television series casualty in [MASK], as " kieron fletcher ". boulter starred hooker the [MASK] film mercenaries directed by paris leonti. [SEP] [CLS] [SEP] [CLS] [MASK] = career = = [SEP] [CLS] [SEP] [CLS]']
Predictions for mask at index 32: ['char']
Predictions for mask at index 39: [',']
Predictions for mask at index 40: ['bo']
Predictions for mask at index 41: ['##ult']
Predictions for mask at index 50: ['@']
Predictions for mask at index 52: ['@']
Predictions for mask at index 57: ['the']
Predictions for mask at index 64: ['followed']
Predictions for mask at index 72: ['casualty']
Predictions for mask at index 79: ['a']
Predictions for mask at index 84: ['episodes']
Predictions for mask at index 91: ['2009']
Predictions for mask at index 106: ['2009']
Predictions for mask at index 119: ['=']
['in the london signed of hammersmith and fulham. boulter starred in two films in 2008, daylight robbery by filmmaker paris leonti, and donkey punch directed by charly blackburn. in may 2008, boulter made a guest appearance on a two @ - @ part episode arc of the television series waking the dead, followed by an appearance on swamps television series casualty in schooling 2008. he had a recurring role in ten episodes of the television series casualty in 2009, as " kieron fletcher ". boulter starred hooker the 2009 film mercenaries directed by paris leonti. [SEP] [CLS] [SEP] [CLS] = = career = = [SEP] [CLS] [SEP] [CLS]']
****************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************

In [ ]:
for block in lm_datasets["test"][:3]["input_ids"]:
  print(tokenizer_infer.decode(block))
  print("*"*50)

[CLS] [SEP] [CLS] = robert boulter = [SEP] [CLS] [SEP] [CLS] robert boulter is an english film, television and theatre actor. he had a guest @ - @ starring role on the television series the bill in 2000. this was followed by a starring role in the play herons written by simon stephens, which was performed in 2001 at the royal court theatre. he had a guest role in the television series judge john deed in 2002. in 2004 boulter landed a role as " craig " in the episode " teddy ' s story " of the television series the long firm ; he starred alongside actors mark strong and derek jacobi.
**************************************************
he was cast in the 2005 theatre productions of the philip ridley play mercury fur, which was performed at the drum theatre in plymouth and the menier chocolate factory in london. he was directed by john tiffany and starred alongside ben whishaw, shane zaza, harry kent, fraser ayres, sophie stanton and dominic hall. [SEP] [CLS] in 2006, boulter starred alongside whishaw in the play citizenship written by mark ravenhill. he appeared on a 2006 episode of the television series, doctors, followed by a role in the 2007 theatre production of how to curse directed by josie rourke. how to curse was performed at bush theatre
**************************************************
in the london borough of hammersmith and fulham. boulter starred in two films in 2008, daylight robbery by filmmaker paris leonti, and donkey punch directed by olly blackburn. in may 2008, boulter made a guest appearance on a two @ - @ part episode arc of the television series waking the dead, followed by an appearance on the television series survivors in november 2008. he had a recurring role in ten episodes of the television series casualty in 2010, as " kieron fletcher ". boulter starred in the 2011 film mercenaries directed by paris leonti. [SEP] [CLS] [SEP] [CLS] = = career = = [SEP] [CLS] [SEP] [CLS]
**************************************************

2)part of sentnces/Inference on the random sentence

single_mask

In [ ]:
#text = "the 2005 theatre productions of the Philip Ridley play Mercury Fur , which was performed at the drum theatre in [MASK]."
text = "This is a great [MASK]."

inputs = tokenizer_infer(text, return_tensors="pt").to(model_infer.device)# to bring input tensor at gpu (selected level)
print(inputs)
token_logits = model_infer(**inputs).logits

# Find the location of [MASK] and extract its logits
mask_token_index = torch.where(inputs["input_ids"] == tokenizer_infer.mask_token_id)[1]
mask_token_logits = token_logits[0, mask_token_index, :]
# Pick the [MASK] candidates with the highest logits
top_5_tokens = torch.topk(mask_token_logits, 5, dim=-1).indices[0].tolist()

for token in top_5_tokens:
    print(f"'>>> {text.replace(tokenizer_infer.mask_token, tokenizer_infer.decode([token]))}'")

{'input_ids': tensor([[ 101, 2023, 2003, 1037, 2307,  103, 1012,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1]])}
'>>> This is a great idea.'
'>>> This is a great deal.'
'>>> This is a great success.'
'>>> This is a great adventure.'
'>>> This is a great relief.'

multiple_masks

In [ ]:
text = "the 2005 theatre productions of the Philip Ridley play Mercury Fur , which [MASK] performed at the drum theatre in [MASK]."
#text = "This is a great [MASK]."

inputs = tokenizer_infer(text, return_tensors="pt").to(model_infer.device)# to bring input tensor at gpu (selected level)
print(inputs)
token_logits = model_infer(**inputs).logits

# Find where the mask tokens are located
mask_token_indices = torch.where(
    inputs["input_ids"] == tokenizer_infer.mask_token_id
)[1]

# Extract predictions for each mask index
for idx in mask_token_indices:
  mask_logits = token_logits[0, idx, :]
  top_tokens = torch.topk(mask_logits, k=5, dim=-1).indices

  decoded_words = [tokenizer_infer.decode([token]) for token in top_tokens]
  print(f"Predictions for mask at index {idx.item()}: {decoded_words}")

{'input_ids': tensor([[  101,  1996,  2384,  3004,  5453,  1997,  1996,  5170, 20608,  2377,
          8714,  6519,  1010,  2029,   103,  2864,  2012,  1996,  6943,  3004,
          1999,   103,  1012,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}
Predictions for mask at index 14: ['was', 'were', 'also', 'is', 'he']
Predictions for mask at index 21: ['london', 'dublin', 'manchester', 'melbourne', 'edinburgh']

# Functions of Datacollator

*   **Common function(mlm =False or mlm= some fraction<=0.15)**

**DataCollatorForLanguageModeling** converts list of identical to something analogous to dictionaries of same keylist with values concatanation of individual dict chunks inside input list for given keys.

Apart from DataCollatorForLanguageModeling's function to PAD variable tokens to local batch_max_length and inserting -100 as tokens for PAD in input_ids, and creates labels on fly.

*   **Specific func(when mlm<=0.15 i.e. some fraction when collating for masked language model)**

Randomly assigns given fraction [MASK] in text and subsitutes input_ids tokens as **tokenizer.mask_token_id** and retains **labels token values at for mask positions, and assigns rest as -100**