In [ ]:
# If there's a GPU available...
import torch
if torch.cuda.is_available():

    # Tell PyTorch to use the GPU.
    device = torch.device("cuda")

    print('There are %d GPU(s) available.' % torch.cuda.device_count())

    print('We will use the GPU:', torch.cuda.get_device_name(0))

# If not...
else:
    print('No GPU available, using the CPU instead.')
    device = torch.device("cpu")

There are 1 GPU(s) available.
We will use the GPU: Tesla T4

Please make sure the outputs of above step confirms notebook to be in GPU mode. Else change it by going to Edit -->Notebook settings -->GPU (under Hardware acclerator drop down)

In [ ]:
from google.colab import drive
drive.mount('/gdrive', force_remount=True)
import os

Mounted at /gdrive

In [ ]:
os.listdir()

['.config', 'sample_data']

**0th evel**

In [ ]:
INPUT_DIR ='/gdrive/MyDrive/heirarchical_classifier_level_0'
test_csv_path ='/gdrive/MyDrive/heirarchical_classifier_ML/data.csv'
cat_lab_path ='/gdrive/MyDrive/heirarchical_classifier_level_0/cat_label_map.json'

MAX_LEN =512

In [ ]:
!pip3 install transformers

Collecting transformers
  Downloading transformers-4.10.2-py3-none-any.whl (2.8 MB)
     |████████████████████████████████| 2.8 MB 5.8 MB/s
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.7/dist-packages (from transformers) (4.62.2)
Collecting pyyaml>=5.1
  Downloading PyYAML-5.4.1-cp37-cp37m-manylinux1_x86_64.whl (636 kB)
     |████████████████████████████████| 636 kB 69.4 MB/s
Collecting huggingface-hub>=0.0.12
  Downloading huggingface_hub-0.0.17-py3-none-any.whl (52 kB)
     |████████████████████████████████| 52 kB 2.1 MB/s
Requirement already satisfied: filelock in /usr/local/lib/python3.7/dist-packages (from transformers) (3.0.12)
Collecting sacremoses
  Downloading sacremoses-0.0.45-py3-none-any.whl (895 kB)
     |████████████████████████████████| 895 kB 61.6 MB/s
Collecting tokenizers<0.11,>=0.10.1
  Downloading tokenizers-0.10.3-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (3.3 MB)
     |████████████████████████████████| 3.3 MB 58.0 MB/s
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.7/dist-packages (from transformers) (1.19.5)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.7/dist-packages (from transformers) (4.8.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.7/dist-packages (from transformers) (2019.12.20)
Requirement already satisfied: packaging in /usr/local/lib/python3.7/dist-packages (from transformers) (21.0)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from transformers) (2.23.0)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from huggingface-hub>=0.0.12->transformers) (3.7.4.3)
Requirement already satisfied: pyparsing>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging->transformers) (2.4.7)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->transformers) (3.5.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->transformers) (1.24.3)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->transformers) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->transformers) (2021.5.30)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->transformers) (2.10)
Requirement already satisfied: joblib in /usr/local/lib/python3.7/dist-packages (from sacremoses->transformers) (1.0.1)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from sacremoses->transformers) (1.15.0)
Requirement already satisfied: click in /usr/local/lib/python3.7/dist-packages (from sacremoses->transformers) (7.1.2)
Installing collected packages: tokenizers, sacremoses, pyyaml, huggingface-hub, transformers
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13
Successfully installed huggingface-hub-0.0.17 pyyaml-5.4.1 sacremoses-0.0.45 tokenizers-0.10.3 transformers-4.10.2

In [ ]:
import torch
from transformers import BertTokenizer, BertForSequenceClassification
import json

In [ ]:
from keras.preprocessing.sequence import pad_sequences

In [ ]:
tokenizer_0 = BertTokenizer.from_pretrained(INPUT_DIR)

filename_0 = open(cat_lab_path, 'r')
cat_lab_0 = json.load(filename_0)

In [ ]:
print(cat_lab_0)
print(type(cat_lab_0))

{'pet supplies': 0, 'health personal care': 1, 'grocery gourmet food': 2, 'toys games': 3, 'beauty': 4, 'baby products': 5}
<class 'dict'>

**Preprocess class**

In [ ]:
from nltk.tokenize import sent_tokenize
import hashlib
import pandas as pd

In [ ]:
import nltk
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    |
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/abc.zip.
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/alpino.zip.
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/biocreative_ppi.zip.
[nltk_data]    | Downloading package brown to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/brown.zip.
[nltk_data]    | Downloading package brown_tei to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/brown_tei.zip.
[nltk_data]    | Downloading package cess_cat to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/cess_cat.zip.
[nltk_data]    | Downloading package cess_esp to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/cess_esp.zip.
[nltk_data]    | Downloading package chat80 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/chat80.zip.
[nltk_data]    | Downloading package city_database to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/city_database.zip.
[nltk_data]    | Downloading package cmudict to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/cmudict.zip.
[nltk_data]    | Downloading package comparative_sentences to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/comparative_sentences.zip.
[nltk_data]    | Downloading package comtrans to /root/nltk_data...
[nltk_data]    | Downloading package conll2000 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/conll2000.zip.
[nltk_data]    | Downloading package conll2002 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/conll2002.zip.
[nltk_data]    | Downloading package conll2007 to /root/nltk_data...
[nltk_data]    | Downloading package crubadan to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/crubadan.zip.
[nltk_data]    | Downloading package dependency_treebank to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/dependency_treebank.zip.
[nltk_data]    | Downloading package dolch to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/dolch.zip.
[nltk_data]    | Downloading package europarl_raw to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/europarl_raw.zip.
[nltk_data]    | Downloading package floresta to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/floresta.zip.
[nltk_data]    | Downloading package framenet_v15 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/framenet_v15.zip.
[nltk_data]    | Downloading package framenet_v17 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/framenet_v17.zip.
[nltk_data]    | Downloading package gazetteers to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/gazetteers.zip.
[nltk_data]    | Downloading package genesis to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/genesis.zip.
[nltk_data]    | Downloading package gutenberg to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/gutenberg.zip.
[nltk_data]    | Downloading package ieer to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/ieer.zip.
[nltk_data]    | Downloading package inaugural to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/inaugural.zip.
[nltk_data]    | Downloading package indian to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/indian.zip.
[nltk_data]    | Downloading package jeita to /root/nltk_data...
[nltk_data]    | Downloading package kimmo to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/kimmo.zip.
[nltk_data]    | Downloading package knbc to /root/nltk_data...
[nltk_data]    | Downloading package lin_thesaurus to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/lin_thesaurus.zip.
[nltk_data]    | Downloading package mac_morpho to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/mac_morpho.zip.
[nltk_data]    | Downloading package machado to /root/nltk_data...
[nltk_data]    | Downloading package masc_tagged to /root/nltk_data...
[nltk_data]    | Downloading package moses_sample to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping models/moses_sample.zip.
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/movie_reviews.zip.
[nltk_data]    | Downloading package names to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/names.zip.
[nltk_data]    | Downloading package nombank.1.0 to /root/nltk_data...
[nltk_data]    | Downloading package nps_chat to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/nps_chat.zip.
[nltk_data]    | Downloading package omw to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/omw.zip.
[nltk_data]    | Downloading package opinion_lexicon to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/opinion_lexicon.zip.
[nltk_data]    | Downloading package paradigms to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/paradigms.zip.
[nltk_data]    | Downloading package pil to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/pil.zip.
[nltk_data]    | Downloading package pl196x to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/pl196x.zip.
[nltk_data]    | Downloading package ppattach to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/ppattach.zip.
[nltk_data]    | Downloading package problem_reports to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/problem_reports.zip.
[nltk_data]    | Downloading package propbank to /root/nltk_data...
[nltk_data]    | Downloading package ptb to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/ptb.zip.
[nltk_data]    | Downloading package product_reviews_1 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/product_reviews_1.zip.
[nltk_data]    | Downloading package product_reviews_2 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/product_reviews_2.zip.
[nltk_data]    | Downloading package pros_cons to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/pros_cons.zip.
[nltk_data]    | Downloading package qc to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/qc.zip.
[nltk_data]    | Downloading package reuters to /root/nltk_data...
[nltk_data]    | Downloading package rte to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/rte.zip.
[nltk_data]    | Downloading package semcor to /root/nltk_data...
[nltk_data]    | Downloading package senseval to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/senseval.zip.
[nltk_data]    | Downloading package sentiwordnet to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/sentiwordnet.zip.
[nltk_data]    | Downloading package sentence_polarity to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/sentence_polarity.zip.
[nltk_data]    | Downloading package shakespeare to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/shakespeare.zip.
[nltk_data]    | Downloading package sinica_treebank to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/sinica_treebank.zip.
[nltk_data]    | Downloading package smultron to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/smultron.zip.
[nltk_data]    | Downloading package state_union to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/state_union.zip.
[nltk_data]    | Downloading package stopwords to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/stopwords.zip.
[nltk_data]    | Downloading package subjectivity to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/subjectivity.zip.
[nltk_data]    | Downloading package swadesh to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/swadesh.zip.
[nltk_data]    | Downloading package switchboard to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/switchboard.zip.
[nltk_data]    | Downloading package timit to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/timit.zip.
[nltk_data]    | Downloading package toolbox to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/toolbox.zip.
[nltk_data]    | Downloading package treebank to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/treebank.zip.
[nltk_data]    | Downloading package twitter_samples to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/twitter_samples.zip.
[nltk_data]    | Downloading package udhr to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/udhr.zip.
[nltk_data]    | Downloading package udhr2 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/udhr2.zip.
[nltk_data]    | Downloading package unicode_samples to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/unicode_samples.zip.
[nltk_data]    | Downloading package universal_treebanks_v20 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    | Downloading package verbnet to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/verbnet.zip.
[nltk_data]    | Downloading package verbnet3 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/verbnet3.zip.
[nltk_data]    | Downloading package webtext to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/webtext.zip.
[nltk_data]    | Downloading package wordnet to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/wordnet.zip.
[nltk_data]    | Downloading package wordnet_ic to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/wordnet_ic.zip.
[nltk_data]    | Downloading package words to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/words.zip.
[nltk_data]    | Downloading package ycoe to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/ycoe.zip.
[nltk_data]    | Downloading package rslp to /root/nltk_data...
[nltk_data]    |   Unzipping stemmers/rslp.zip.
[nltk_data]    | Downloading package maxent_treebank_pos_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/maxent_treebank_pos_tagger.zip.
[nltk_data]    | Downloading package universal_tagset to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/universal_tagset.zip.
[nltk_data]    | Downloading package maxent_ne_chunker to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping chunkers/maxent_ne_chunker.zip.
[nltk_data]    | Downloading package punkt to /root/nltk_data...
[nltk_data]    |   Unzipping tokenizers/punkt.zip.
[nltk_data]    | Downloading package book_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/book_grammars.zip.
[nltk_data]    | Downloading package sample_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/sample_grammars.zip.
[nltk_data]    | Downloading package spanish_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/spanish_grammars.zip.
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/basque_grammars.zip.
[nltk_data]    | Downloading package large_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/large_grammars.zip.
[nltk_data]    | Downloading package tagsets to /root/nltk_data...
[nltk_data]    |   Unzipping help/tagsets.zip.
[nltk_data]    | Downloading package snowball_data to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    | Downloading package bllip_wsj_no_aux to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping models/bllip_wsj_no_aux.zip.
[nltk_data]    | Downloading package word2vec_sample to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping models/word2vec_sample.zip.
[nltk_data]    | Downloading package panlex_swadesh to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    | Downloading package mte_teip5 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/mte_teip5.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_ru.zip.
[nltk_data]    | Downloading package perluniprops to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping misc/perluniprops.zip.
[nltk_data]    | Downloading package nonbreaking_prefixes to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/nonbreaking_prefixes.zip.
[nltk_data]    | Downloading package vader_lexicon to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    | Downloading package porter_test to /root/nltk_data...
[nltk_data]    |   Unzipping stemmers/porter_test.zip.
[nltk_data]    | Downloading package wmt15_eval to /root/nltk_data...
[nltk_data]    |   Unzipping models/wmt15_eval.zip.
[nltk_data]    | Downloading package mwa_ppdb to /root/nltk_data...
[nltk_data]    |   Unzipping misc/mwa_ppdb.zip.
[nltk_data]    |
[nltk_data]  Done downloading collection all

True

In [ ]:
from math import ceil

In [ ]:
#preprocessing

class preprocessing:

  def __init__(self, df):
    self.df =df

  def preprocess(self, level, parent_class, present_class):
    if(level ==0):
        # print('+'*70)

      self.df['Title'] = self.df['Title'].fillna('')
      self.df['Text'] = self.df['Text'].fillna('')

      X = list(self.df['Title']+'. '+self.df['Text'])
      Y = [cat_lab_0[el] for el in list(self.df['Cat1'])]

    self.X =X
    self.Y =Y

  def input_ids_converter(self):

    self.input_ids = []

    for sent in self.X:
      encoded_sent = tokenizer_0.encode(
                        sent,                      # Sentence to encode.
                        add_special_tokens = True)

      self.input_ids.append(encoded_sent)


    # print('Max sentence length: ', max([len(sen) for sen in self.input_ids]))


    self.input_ids = pad_sequences(self.input_ids, maxlen=MAX_LEN, dtype="long",
                          value=0, truncating="post", padding="post")


  def masking(self):

    self.attention_masks = []

    # For each sentence...
    for sent in self.input_ids:

        att_mask = [int(token_id > 0) for token_id in sent]

        # Store the attention mask for this sentence.
        self.attention_masks.append(att_mask)

In [ ]:
test_df = pd.read_csv(test_csv_path)

prep = preprocessing(test_df)

prep.preprocess(0, 'NULL', 'NULL')
prep.input_ids_converter()
prep.masking()

input_ids0 =prep.input_ids
att_masks0 =prep.attention_masks
Y0= prep.Y


print(prep.X[0])
print((input_ids0[0]))
print(att_masks0[0])

Token indices sequence length is longer than the specified maximum sequence length for this model (572 > 512). Running this sequence through the model will result in indexing errors

PetSafe Staywell Pet Door with Clear Hard Flap. We've only had it installed about 2 weeks. So far it works great. My chubby collie & old black lab are both going in and out easily. It was easy to install. It was hanging up a little when closing but seems to be working through that. It was supposed to be a clear door & it is not. Very disappointed in that.
[  101 18551 10354  2063  2994  4381  9004  2341  2007  3154  2524 20916
  1012  2057  1005  2310  2069  2018  2009  5361  2055  1016  3134  1012
  2061  2521  2009  2573  2307  1012  2026 14684 14075  8902  8751  1004
  2214  2304  6845  2024  2119  2183  1999  1998  2041  4089  1012  2009
  2001  3733  2000 16500  1012  2009  2001  5689  2039  1037  2210  2043
  5494  2021  3849  2000  2022  2551  2083  2008  1012  2009  2001  4011
  2000  2022  1037  3154  2341  1004  2009  2003  2025  1012  2200  9364
  1999  2008  1012   102     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [ ]:
print(len(input_ids0))
print(input_ids0.shape)
print(Y0[0])

10000
(10000, 512)
0

In [ ]:
# Convert all inputs and labels into torch tensors, the required datatype
# for our model.
test_inputs0 = torch.tensor(input_ids0)
test_labels0 = torch.tensor(Y0)
test_masks0 = torch.tensor(att_masks0)

In [ ]:
from torch.utils.data import TensorDataset, DataLoader, SequentialSampler

batch_size = 10
# Create the DataLoader for our validation set.
test_data0 = TensorDataset(test_inputs0, test_masks0, test_labels0)
test_sampler0 = SequentialSampler(test_data0)
test_dataloader0 = DataLoader(test_data0, sampler=test_sampler0, batch_size=batch_size)

In [ ]:
model_0 =BertForSequenceClassification.from_pretrained(INPUT_DIR)
model_0.cuda()

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0): BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
        (1): BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
        (2): BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
        (3): BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
        (4): BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
        (5): BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
        (6): BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
        (7): BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
        (8): BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
        (9): BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
        (10): BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
        (11): BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (pooler): BertPooler(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (activation): Tanh()
    )
  )
  (dropout): Dropout(p=0.1, inplace=False)
  (classifier): Linear(in_features=768, out_features=6, bias=True)
)

In [ ]:
# Function to calculate the accuracy of our predictions vs labels
def flat_accuracy(preds, labels, ls):
    pred_flat = np.argmax(preds, axis=1).flatten()
    ls+=list(pred_flat)
    labels_flat = labels.flatten()
    return np.sum(pred_flat == labels_flat) / len(labels_flat), ls

def weighted_f1(preds, labels):
    preds_flat = np.argmax(preds, axis=1).flatten()
    labels_flat = labels.flatten()
    return f1_score(labels_flat, preds_flat, average='weighted')

def format_time(elapsed):
    '''
    Takes a time in seconds and returns a string hh:mm:ss
    '''
    # Round to the nearest second.
    elapsed_rounded = int(round((elapsed)))

    # Format as hh:mm:ss
    return str(datetime.timedelta(seconds=elapsed_rounded))

In [ ]:
from tqdm import tqdm

import numpy as np
import time

from sklearn.metrics import f1_score
import datetime

In [ ]:
print("")
print("Running tseting...")

t0 = time.time()

# Put model in evaluation mode to evaluate loss on the validation set
model_0.eval()

# Tracking variables

ls_level0_predicted=[]
eval_loss_0, eval_accuracy_0, eval_f1_0 = 0, 0, 0
nb_eval_steps_0, nb_eval_examples_0 = 0, 0

# Evaluate data for one epoch
for batch in tqdm(test_dataloader0):
  # Add batch to GPU
  batch = tuple(t.to(device) for t in batch)

  # Unpack the inputs from our dataloader
  b_input_ids0, b_input_mask0, b_labels0 = batch

  # Telling the model not to compute or store gradients, saving memory and speeding up validation
  with torch.no_grad():
    # Forward pass, calculate logit predictions
    # token_type_ids is for the segment ids, but we only have a single sentence here.
    # See https://github.com/huggingface/transformers/blob/5bfcd0485ece086ebcbed2d008813037968a9e58/examples/run_glue.py#L258
    outputs = model_0(b_input_ids0, token_type_ids=None, attention_mask=b_input_mask0)

  logits0 = outputs[0]

  # Move logits and labels to CPU
  logits0 = logits0.detach().cpu().numpy()
  label_ids0 = b_labels0.to('cpu').numpy()

  # Calculate the accuracy for this batch of test sentences.
  tmp_eval_accuracy,ls_level0_predicted  = flat_accuracy(logits0, label_ids0, ls_level0_predicted)

  # Accumulate the total accuracy.
  eval_accuracy_0 += tmp_eval_accuracy

  #Calculate the f1 for this batch and accumulate it
  temp_weighted_f1 = weighted_f1(logits0, label_ids0)
  eval_f1_0 +=temp_weighted_f1

  # Track the number of batches
  nb_eval_steps_0 += 1


# pred_flat = np.argmax(logits, axis=1).flatten()
# label_flat =label_ids.flatten()

# new_f1 =f1_score(label_flat, pred_flat, average='weighted')

new_f1_0 = eval_f1_0/nb_eval_steps_0
accuracy_0 = eval_accuracy_0/nb_eval_steps_0
# Report the final accuracy for this validation run.
print("  Accuracy: {0:.2f}".format(eval_accuracy_0/nb_eval_steps_0))
print("  Validation took: {:}".format(format_time(time.time() - t0)))
print("f1:-", new_f1_0)

Running tseting...

100%|██████████| 1000/1000 [06:39<00:00,  2.50it/s]

  Accuracy: 0.98
  Validation took: 0:06:40
f1:- 0.977551587301587

In [ ]:
print(len(ls_level0_predicted))

10000

In [ ]:
ls_level0_predictclass =[k for el in tqdm(ls_level0_predicted) for k in cat_lab_0.keys() if(el ==cat_lab_0[k])]

100%|██████████| 10000/10000 [00:00<00:00, 511781.34it/s]

In [ ]:
ls_level0_predictclass[:20]

['pet supplies',
 'pet supplies',
 'health personal care',
 'grocery gourmet food',
 'pet supplies',
 'pet supplies',
 'health personal care',
 'toys games',
 'beauty',
 'beauty',
 'health personal care',
 'health personal care',
 'toys games',
 'beauty',
 'grocery gourmet food',
 'beauty',
 'beauty',
 'pet supplies',
 'health personal care',
 'pet supplies']

In [ ]:
test_df['Cat1_predicted'] =ls_level0_predictclass

In [ ]:
test_df.to_excel(INPUT_DIR+'/'+'heirarchical_classifier_cat1_pred.xlsx', index=False)

**1st level predictions**

In [ ]:
import torch
from transformers import BertTokenizer, BertForSequenceClassification
import json

In [ ]:
from keras.preprocessing.sequence import pad_sequences

In [ ]:
from nltk.tokenize import sent_tokenize
import hashlib
import pandas as pd

In [ ]:
import nltk
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    |
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package biocreative_ppi is already up-to-date!
[nltk_data]    | Downloading package brown to /root/nltk_data...
[nltk_data]    |   Package brown is already up-to-date!
[nltk_data]    | Downloading package brown_tei to /root/nltk_data...
[nltk_data]    |   Package brown_tei is already up-to-date!
[nltk_data]    | Downloading package cess_cat to /root/nltk_data...
[nltk_data]    |   Package cess_cat is already up-to-date!
[nltk_data]    | Downloading package cess_esp to /root/nltk_data...
[nltk_data]    |   Package cess_esp is already up-to-date!
[nltk_data]    | Downloading package chat80 to /root/nltk_data...
[nltk_data]    |   Package chat80 is already up-to-date!
[nltk_data]    | Downloading package city_database to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package city_database is already up-to-date!
[nltk_data]    | Downloading package cmudict to /root/nltk_data...
[nltk_data]    |   Package cmudict is already up-to-date!
[nltk_data]    | Downloading package comparative_sentences to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package comparative_sentences is already up-to-
[nltk_data]    |       date!
[nltk_data]    | Downloading package comtrans to /root/nltk_data...
[nltk_data]    |   Package comtrans is already up-to-date!
[nltk_data]    | Downloading package conll2000 to /root/nltk_data...
[nltk_data]    |   Package conll2000 is already up-to-date!
[nltk_data]    | Downloading package conll2002 to /root/nltk_data...
[nltk_data]    |   Package conll2002 is already up-to-date!
[nltk_data]    | Downloading package conll2007 to /root/nltk_data...
[nltk_data]    |   Package conll2007 is already up-to-date!
[nltk_data]    | Downloading package crubadan to /root/nltk_data...
[nltk_data]    |   Package crubadan is already up-to-date!
[nltk_data]    | Downloading package dependency_treebank to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package dependency_treebank is already up-to-date!
[nltk_data]    | Downloading package dolch to /root/nltk_data...
[nltk_data]    |   Package dolch is already up-to-date!
[nltk_data]    | Downloading package europarl_raw to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package europarl_raw is already up-to-date!
[nltk_data]    | Downloading package floresta to /root/nltk_data...
[nltk_data]    |   Package floresta is already up-to-date!
[nltk_data]    | Downloading package framenet_v15 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package framenet_v15 is already up-to-date!
[nltk_data]    | Downloading package framenet_v17 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package framenet_v17 is already up-to-date!
[nltk_data]    | Downloading package gazetteers to /root/nltk_data...
[nltk_data]    |   Package gazetteers is already up-to-date!
[nltk_data]    | Downloading package genesis to /root/nltk_data...
[nltk_data]    |   Package genesis is already up-to-date!
[nltk_data]    | Downloading package gutenberg to /root/nltk_data...
[nltk_data]    |   Package gutenberg is already up-to-date!
[nltk_data]    | Downloading package ieer to /root/nltk_data...
[nltk_data]    |   Package ieer is already up-to-date!
[nltk_data]    | Downloading package inaugural to /root/nltk_data...
[nltk_data]    |   Package inaugural is already up-to-date!
[nltk_data]    | Downloading package indian to /root/nltk_data...
[nltk_data]    |   Package indian is already up-to-date!
[nltk_data]    | Downloading package jeita to /root/nltk_data...
[nltk_data]    |   Package jeita is already up-to-date!
[nltk_data]    | Downloading package kimmo to /root/nltk_data...
[nltk_data]    |   Package kimmo is already up-to-date!
[nltk_data]    | Downloading package knbc to /root/nltk_data...
[nltk_data]    |   Package knbc is already up-to-date!
[nltk_data]    | Downloading package lin_thesaurus to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package lin_thesaurus is already up-to-date!
[nltk_data]    | Downloading package mac_morpho to /root/nltk_data...
[nltk_data]    |   Package mac_morpho is already up-to-date!
[nltk_data]    | Downloading package machado to /root/nltk_data...
[nltk_data]    |   Package machado is already up-to-date!
[nltk_data]    | Downloading package masc_tagged to /root/nltk_data...
[nltk_data]    |   Package masc_tagged is already up-to-date!
[nltk_data]    | Downloading package moses_sample to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package moses_sample is already up-to-date!
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package movie_reviews is already up-to-date!
[nltk_data]    | Downloading package names to /root/nltk_data...
[nltk_data]    |   Package names is already up-to-date!
[nltk_data]    | Downloading package nombank.1.0 to /root/nltk_data...
[nltk_data]    |   Package nombank.1.0 is already up-to-date!
[nltk_data]    | Downloading package nps_chat to /root/nltk_data...
[nltk_data]    |   Package nps_chat is already up-to-date!
[nltk_data]    | Downloading package omw to /root/nltk_data...
[nltk_data]    |   Package omw is already up-to-date!
[nltk_data]    | Downloading package opinion_lexicon to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package opinion_lexicon is already up-to-date!
[nltk_data]    | Downloading package paradigms to /root/nltk_data...
[nltk_data]    |   Package paradigms is already up-to-date!
[nltk_data]    | Downloading package pil to /root/nltk_data...
[nltk_data]    |   Package pil is already up-to-date!
[nltk_data]    | Downloading package pl196x to /root/nltk_data...
[nltk_data]    |   Package pl196x is already up-to-date!
[nltk_data]    | Downloading package ppattach to /root/nltk_data...
[nltk_data]    |   Package ppattach is already up-to-date!
[nltk_data]    | Downloading package problem_reports to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package problem_reports is already up-to-date!
[nltk_data]    | Downloading package propbank to /root/nltk_data...
[nltk_data]    |   Package propbank is already up-to-date!
[nltk_data]    | Downloading package ptb to /root/nltk_data...
[nltk_data]    |   Package ptb is already up-to-date!
[nltk_data]    | Downloading package product_reviews_1 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package product_reviews_1 is already up-to-date!
[nltk_data]    | Downloading package product_reviews_2 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package product_reviews_2 is already up-to-date!
[nltk_data]    | Downloading package pros_cons to /root/nltk_data...
[nltk_data]    |   Package pros_cons is already up-to-date!
[nltk_data]    | Downloading package qc to /root/nltk_data...
[nltk_data]    |   Package qc is already up-to-date!
[nltk_data]    | Downloading package reuters to /root/nltk_data...
[nltk_data]    |   Package reuters is already up-to-date!
[nltk_data]    | Downloading package rte to /root/nltk_data...
[nltk_data]    |   Package rte is already up-to-date!
[nltk_data]    | Downloading package semcor to /root/nltk_data...
[nltk_data]    |   Package semcor is already up-to-date!
[nltk_data]    | Downloading package senseval to /root/nltk_data...
[nltk_data]    |   Package senseval is already up-to-date!
[nltk_data]    | Downloading package sentiwordnet to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package sentiwordnet is already up-to-date!
[nltk_data]    | Downloading package sentence_polarity to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package sentence_polarity is already up-to-date!
[nltk_data]    | Downloading package shakespeare to /root/nltk_data...
[nltk_data]    |   Package shakespeare is already up-to-date!
[nltk_data]    | Downloading package sinica_treebank to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package sinica_treebank is already up-to-date!
[nltk_data]    | Downloading package smultron to /root/nltk_data...
[nltk_data]    |   Package smultron is already up-to-date!
[nltk_data]    | Downloading package state_union to /root/nltk_data...
[nltk_data]    |   Package state_union is already up-to-date!
[nltk_data]    | Downloading package stopwords to /root/nltk_data...
[nltk_data]    |   Package stopwords is already up-to-date!
[nltk_data]    | Downloading package subjectivity to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package subjectivity is already up-to-date!
[nltk_data]    | Downloading package swadesh to /root/nltk_data...
[nltk_data]    |   Package swadesh is already up-to-date!
[nltk_data]    | Downloading package switchboard to /root/nltk_data...
[nltk_data]    |   Package switchboard is already up-to-date!
[nltk_data]    | Downloading package timit to /root/nltk_data...
[nltk_data]    |   Package timit is already up-to-date!
[nltk_data]    | Downloading package toolbox to /root/nltk_data...
[nltk_data]    |   Package toolbox is already up-to-date!
[nltk_data]    | Downloading package treebank to /root/nltk_data...
[nltk_data]    |   Package treebank is already up-to-date!
[nltk_data]    | Downloading package twitter_samples to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package twitter_samples is already up-to-date!
[nltk_data]    | Downloading package udhr to /root/nltk_data...
[nltk_data]    |   Package udhr is already up-to-date!
[nltk_data]    | Downloading package udhr2 to /root/nltk_data...
[nltk_data]    |   Package udhr2 is already up-to-date!
[nltk_data]    | Downloading package unicode_samples to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package unicode_samples is already up-to-date!
[nltk_data]    | Downloading package universal_treebanks_v20 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package universal_treebanks_v20 is already up-to-
[nltk_data]    |       date!
[nltk_data]    | Downloading package verbnet to /root/nltk_data...
[nltk_data]    |   Package verbnet is already up-to-date!
[nltk_data]    | Downloading package verbnet3 to /root/nltk_data...
[nltk_data]    |   Package verbnet3 is already up-to-date!
[nltk_data]    | Downloading package webtext to /root/nltk_data...
[nltk_data]    |   Package webtext is already up-to-date!
[nltk_data]    | Downloading package wordnet to /root/nltk_data...
[nltk_data]    |   Package wordnet is already up-to-date!
[nltk_data]    | Downloading package wordnet_ic to /root/nltk_data...
[nltk_data]    |   Package wordnet_ic is already up-to-date!
[nltk_data]    | Downloading package words to /root/nltk_data...
[nltk_data]    |   Package words is already up-to-date!
[nltk_data]    | Downloading package ycoe to /root/nltk_data...
[nltk_data]    |   Package ycoe is already up-to-date!
[nltk_data]    | Downloading package rslp to /root/nltk_data...
[nltk_data]    |   Package rslp is already up-to-date!
[nltk_data]    | Downloading package maxent_treebank_pos_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package maxent_treebank_pos_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package universal_tagset to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package universal_tagset is already up-to-date!
[nltk_data]    | Downloading package maxent_ne_chunker to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package maxent_ne_chunker is already up-to-date!
[nltk_data]    | Downloading package punkt to /root/nltk_data...
[nltk_data]    |   Package punkt is already up-to-date!
[nltk_data]    | Downloading package book_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package book_grammars is already up-to-date!
[nltk_data]    | Downloading package sample_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package sample_grammars is already up-to-date!
[nltk_data]    | Downloading package spanish_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package spanish_grammars is already up-to-date!
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package basque_grammars is already up-to-date!
[nltk_data]    | Downloading package large_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package large_grammars is already up-to-date!
[nltk_data]    | Downloading package tagsets to /root/nltk_data...
[nltk_data]    |   Package tagsets is already up-to-date!
[nltk_data]    | Downloading package snowball_data to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package snowball_data is already up-to-date!
[nltk_data]    | Downloading package bllip_wsj_no_aux to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package bllip_wsj_no_aux is already up-to-date!
[nltk_data]    | Downloading package word2vec_sample to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package word2vec_sample is already up-to-date!
[nltk_data]    | Downloading package panlex_swadesh to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package panlex_swadesh is already up-to-date!
[nltk_data]    | Downloading package mte_teip5 to /root/nltk_data...
[nltk_data]    |   Package mte_teip5 is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_ru is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package perluniprops to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package perluniprops is already up-to-date!
[nltk_data]    | Downloading package nonbreaking_prefixes to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package nonbreaking_prefixes is already up-to-date!
[nltk_data]    | Downloading package vader_lexicon to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package vader_lexicon is already up-to-date!
[nltk_data]    | Downloading package porter_test to /root/nltk_data...
[nltk_data]    |   Package porter_test is already up-to-date!
[nltk_data]    | Downloading package wmt15_eval to /root/nltk_data...
[nltk_data]    |   Package wmt15_eval is already up-to-date!
[nltk_data]    | Downloading package mwa_ppdb to /root/nltk_data...
[nltk_data]    |   Package mwa_ppdb is already up-to-date!
[nltk_data]    |
[nltk_data]  Done downloading collection all

True

In [ ]:
from math import ceil

In [ ]:
from tqdm import tqdm

import numpy as np
import time

from sklearn.metrics import f1_score, accuracy_score
import datetime

In [ ]:
from torch.utils.data import TensorDataset, DataLoader, SequentialSampler

In [ ]:
INPUT_DIR1 ='/gdrive/MyDrive/heirarchical_classifier_level_1'
test_excel_path ='/gdrive/MyDrive/heirarchical_classifier_level_0/heirarchical_classifier_cat1_pred.xlsx'
# cat_lab_path ='/gdrive/MyDrive/heirarchical_classifier_level_1/cat_label_map.json'

MAX_LEN =512

In [ ]:
test_df1 = pd.read_excel(test_excel_path, engine='openpyxl')

In [ ]:
test_df1.head()

    productId  ...        Cat1_predicted
0  B0002AQK70  ...          pet supplies
1  B0002DK8OI  ...          pet supplies
2  B0006VJ6TO  ...  health personal care
3  B000EZSFXA  ...  grocery gourmet food
4  B000KV61FC  ...          pet supplies

[5 rows x 9 columns]

In [ ]:
os.listdir(INPUT_DIR1+'/'+self.first_level_class_mod)

NameError: ignored

In [ ]:
class preprocessing1:

  def __init__(self, df, first_level_class):
    self.first_level_class =first_level_class
    self.first_level_class_mod = first_level_class.replace(' ','_').strip()
    self.df =df
    self.filename = open(INPUT_DIR1+'/'+self.first_level_class_mod+'/'+'cat_label_map.json', 'r')
    self.cat_label = json.load(self.filename)

    # print(INPUT_DIR1+'/'+self.first_level_class_mod)
    self.tokenizer =BertTokenizer.from_pretrained(INPUT_DIR1+'/'+self.first_level_class_mod)
    self.model = BertForSequenceClassification.from_pretrained(INPUT_DIR1+'/'+self.first_level_class_mod)
    self.model.cuda()

  def preprocess(self, level):
    if(level ==1):
      self.df_updated = self.df[self.df['Cat1_predicted'] ==self.first_level_class]
      self.df_updated['Title'] = self.df_updated['Title'].fillna('')
      self.df_updated['Text'] = self.df_updated['Text'].fillna('')

      ls_new=[]
      for r in range(len(self.df_updated.axes[0])):
        di_temp = dict(self.df_updated.iloc[r])

        title =di_temp['Title']
        text = di_temp['Text']
        cat2 =di_temp['Cat2']

        st_hash = di_temp['productId']+di_temp['userId']+ str(di_temp['Time'])

        hash_ =hashlib.sha1(st_hash.encode('utf-8')).hexdigest()

        sent_list = sent_tokenize(text)

        for elm in sent_list:
          di_gran={}
          di_gran['hash'] =hash_
          di_gran['combined_text_granular'] =title+'. '+elm
          di_gran['Cat2'] = cat2

          ls_new.append(di_gran)


      self.df_new = pd.DataFrame(ls_new)

      X = list(self.df_new['combined_text_granular'])
      # Y = [self.cat_label[el] for el in list(self.df_new['Cat2'])]

    self.X =X
    # self.Y =Y

  def input_ids_converter(self):

    self.input_ids = []

    for sent in self.X:
      encoded_sent = self.tokenizer.encode(
                        sent,                      # Sentence to encode.
                        add_special_tokens = True)

      self.input_ids.append(encoded_sent)


    # print('Max sentence length: ', max([len(sen) for sen in self.input_ids]))


    self.input_ids = pad_sequences(self.input_ids, maxlen=MAX_LEN, dtype="long",
                          value=0, truncating="post", padding="post")


  def masking(self):

    self.attention_masks = []

    # For each sentence...
    for sent in self.input_ids:

        att_mask = [int(token_id > 0) for token_id in sent]

        # Store the attention mask for this sentence.
        self.attention_masks.append(att_mask)

  def input_convert(self):
    # Convert all inputs and labels into torch tensors, the required datatype
    # for our model.
    self.test_inputs = torch.tensor(self.input_ids)
    # self.test_labels = torch.tensor(self.Y)
    self.test_masks = torch.tensor(self.attention_masks)

    self.batch_size = 10
    # Create the DataLoader for our validation set.
    self.test_data = TensorDataset(self.test_inputs, self.test_masks)
    # self.test_data = TensorDataset(self.test_inputs, self.test_masks, self.test_labels)
    self.test_sampler = SequentialSampler(self.test_data)
    self.test_dataloader = DataLoader(self.test_data, sampler=self.test_sampler, batch_size=self.batch_size)


  # Function to calculate the accuracy of our predictions vs labels
  # def flat_accuracy(preds, labels, ls):
  #     pred_flat = np.argmax(preds, axis=1).flatten()
  #     ls+=list(pred_flat)
  #     labels_flat = labels.flatten()
  #     return np.sum(pred_flat == labels_flat) / len(labels_flat), ls

  # def weighted_f1(preds, labels):
  #     preds_flat = np.argmax(preds, axis=1).flatten()
  #     labels_flat = labels.flatten()
  #     return f1_score(labels_flat, preds_flat, average='weighted')

  def format_time(self,elapsed):
      '''
      Takes a time in seconds and returns a string hh:mm:ss
      '''
      # Round to the nearest second.
      elapsed_rounded = int(round((elapsed)))

      # Format as hh:mm:ss
      return str(datetime.timedelta(seconds=elapsed_rounded))

  # def model_initialize(self):
  #   model = BertForSequenceClassification(INPUT_DIR1+'/'+self.first_level_class_mod)
  #   model.cuda()
  #   return model


  def feed_forward(self):
    print("")
    print("Running testing...")

    t0 = time.time()

    # Put model in evaluation mode to evaluate loss on the validation set
    self.model.eval()

    # Tracking variables

    self.ls_new=[]
    eval_loss, eval_accuracy, eval_f1 = 0, 0, 0
    nb_eval_steps, nb_eval_examples = 0, 0

    # Evaluate data for one epoch
    for batch in tqdm(self.test_dataloader):
      # Add batch to GPU
      batch = tuple(t.to(device) for t in batch)

      # Unpack the inputs from our dataloader

      # b_input_ids, b_input_mask, b_labels = batch
      b_input_ids, b_input_mask = batch

      # Telling the model not to compute or store gradients, saving memory and speeding up validation
      with torch.no_grad():
        # Forward pass, calculate logit predictions
        # token_type_ids is for the segment ids, but we only have a single sentence here.
        # See https://github.com/huggingface/transformers/blob/5bfcd0485ece086ebcbed2d008813037968a9e58/examples/run_glue.py#L258
        outputs = self.model(b_input_ids, token_type_ids=None, attention_mask=b_input_mask)

      logits = outputs[0]

      # Move logits and labels to CPU
      logits = logits.detach().cpu().numpy()
      # label_ids = b_labels.to('cpu').numpy()

      pred_flat = np.argmax(logits, axis=1).flatten()
      self.ls_new+=list(pred_flat)
      # Calculate the accuracy for this batch of test sentences.
      # tmp_eval_accuracy,self.ls_new  = flat_accuracy(logits, label_ids, self.ls_new)

      # Accumulate the total accuracy.
      # eval_accuracy += tmp_eval_accuracy

      #Calculate the f1 for this batch and accumulate it
      # temp_weighted_f1 = weighted_f1(logits, label_ids)
      # eval_f1 +=temp_weighted_f1

      # Track the number of batches
      nb_eval_steps += 1


    # pred_flat = np.argmax(logits, axis=1).flatten()
    # label_flat =label_ids.flatten()

    # new_f1 =f1_score(label_flat, pred_flat, average='weighted')

    # new_f1 = eval_f1/nb_eval_steps
    # accuracy = eval_accuracy/nb_eval_steps
    # # Report the final accuracy for this validation run.
    # print("  Accuracy: {0:.2f}".format(eval_accuracy/nb_eval_steps))
    # print("f1:-", new_f1)

    print("  Validation took: {:}".format(self.format_time(time.time() - t0)))


  def postprocessing(self):
    self.df_new['Cat2_predicted'] = self.ls_new

    unique_hash_ls =self.df_new['hash'].unique()

    ls_final=[]
    for el in unique_hash_ls:
      df_hash = self.df_new[self.df_new['hash'] ==el]
      mode = df_hash['Cat2_predicted'].mode()[0]# retrieves most probable entities of given column in data frame

      ls_final.append(mode)

    ls_final_class =[k for el in tqdm(ls_final) for k in self.cat_label.keys() if(el ==self.cat_label[k])]
    self.df_updated['Cat2_predicted'] =ls_final_class

In [ ]:
first_level_class_list =["pet supplies", "health personal care", "grocery gourmet food", "toys games", "beauty", "baby products"]

ls_all_class=[]
for class_ in first_level_class_list:
  inference =preprocessing1(test_df1, class_)
  inference.preprocess(1)
  inference.input_ids_converter()
  inference.masking()
  inference.input_convert()
  inference.feed_forward()

  inference.postprocessing()
  predicted_class_df =inference.df_updated

  actual_ls= list(predicted_class_df['Cat2'])
  pred_ls = list(predicted_class_df['Cat2_predicted'])

  print(len(actual_ls))
  print(len(pred_ls))
  accuracy =accuracy_score(actual_ls, pred_ls)
  f1 =f1_score(actual_ls, pred_ls, average='weighted')
  print(accuracy)
  print(f1)

  ls_all_class.append(predicted_class_df)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  0%|          | 0/1570 [2:39:37<?, ?it/s]
  0%|          | 0/1570 [2:31:37<?, ?it/s]

Running testing...

100%|██████████| 712/712 [04:11<00:00,  2.83it/s]

  Validation took: 0:04:11

100%|██████████| 1570/1570 [00:00<00:00, 251722.37it/s]
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:207: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

1570
1570
0.9802547770700637
0.9755541956355999

Running testing...

100%|██████████| 1185/1185 [07:27<00:00,  2.65it/s]

  Validation took: 0:07:28

100%|██████████| 3013/3013 [00:00<00:00, 387390.04it/s]

3013
3013
0.9651510122801195
0.9495610575794913

Running testing...

100%|██████████| 340/340 [02:07<00:00,  2.66it/s]

  Validation took: 0:02:08

100%|██████████| 833/833 [00:00<00:00, 155524.38it/s]

833
833
0.9483793517406963
0.9397694061252172

Running testing...

100%|██████████| 668/668 [04:08<00:00,  2.68it/s]

  Validation took: 0:04:09

100%|██████████| 1745/1745 [00:00<00:00, 144385.80it/s]

1745
1745
0.971919770773639
0.9676749119832367

Running testing...

100%|██████████| 848/848 [05:17<00:00,  2.67it/s]

  Validation took: 0:05:18

100%|██████████| 2122/2122 [00:00<00:00, 454352.60it/s]

2122
2122
0.9736098020735156
0.9620350570919389

Token indices sequence length is longer than the specified maximum sequence length for this model (530 > 512). Running this sequence through the model will result in indexing errors

Running testing...

100%|██████████| 311/311 [01:58<00:00,  2.62it/s]

  Validation took: 0:01:59

100%|██████████| 717/717 [00:00<00:00, 254986.94it/s]

717
717
0.9442119944211994
0.9218949148190531

In [ ]:
df_all_classes = pd.concat(ls_all_class).sort_index()

In [ ]:
len(df_all_classes.axes[0])

10000

In [ ]:
df_all_classes[0:50]

     productId  ...           Cat2_predicted
0   B0002AQK70  ...                     cats
1   B0002DK8OI  ...     bunny rabbit central
2   B0006VJ6TO  ...              health care
3   B000EZSFXA  ...               snack food
4   B000KV61FC  ...                     dogs
5   B000JQALAE  ...                     dogs
6   B000JCCVQU  ...       household supplies
7   B000TA8MKG  ...         novelty gag toys
8   B000093A0U  ...                fragrance
9   B000N2Q1V2  ...                skin care
10  B0000C88FZ  ...            personal care
11  B000CEA08Q  ...       nutrition wellness
12  B000GSNQ8E  ...       action toy figures
13  B00063FBBE  ...                fragrance
14  B0002NYO20  ...           pantry staples
15  B0007CZXQC  ...                fragrance
16  B000A3ZMPA  ...                   makeup
17  B000H121DQ  ...                     dogs
18  B000059Z77  ...       nutrition wellness
19  B000FJ9QLA  ...                     dogs
20  B0002I0O60  ...                     dogs
21  B0002DUTGU  ...              health care
22  B00016X10Y  ...                   makeup
23  B000ES6DPE  ...                     dogs
24  B00001QE9G  ...    stuffed animals plush
25  B000GCUDZO  ...       nutrition wellness
26  B000GL4NPQ  ...                     dogs
27  B00067ZQFG  ...                    herbs
28  B000JIHP88  ...                  nursery
29  B00002N60G  ...       household supplies
30  B0002DGSRO  ...                     cats
31  B000A2REDO  ...       nutrition wellness
32  B0006O10P4  ...                bath body
33  B000OXI4ME  ...                     dogs
34  B00005U2HS  ...       action toy figures
35  B000A7SX0M  ...                     dogs
36  B0002PU7L0  ...                   makeup
37  B000EQGT00  ...       action toy figures
38  B000GWLGG4  ...       nutrition wellness
39  B00009WO07  ...                diapering
40  B0006IQK50  ...                bath body
41  B000LSZVKA  ...        baby toddler toys
42  B0006Q01EI  ...                hair care
43  B0002I0O60  ...                     dogs
44  B00020I8IY  ...       nutrition wellness
45  B000I62MC0  ...  cooking baking supplies
46  B00008BFXL  ...            personal care
47  B000KUHFGM  ...          baby child care
48  B000H7MMP2  ...              health care
49  B000HG84EQ  ...               snack food

[50 rows x 10 columns]

In [ ]:
df_all_classes.to_excel(INPUT_DIR1+'/'+'heirarchical_classifier_cat2_pred.xlsx', index=False)

In [ ]:
  actual_ls= list(df_all_classes['Cat2'])
  pred_ls = list(df_all_classes['Cat2_predicted'])

  print(len(actual_ls))
  print(len(pred_ls))
  accuracy =accuracy_score(actual_ls, pred_ls)
  f1 =f1_score(actual_ls, pred_ls, average='weighted')
  print(accuracy)
  print(f1)

10000
10000
0.9676
0.9675531945098795

In [ ]:
# df_new = inference.df_new
# unique_hash_ls =df_new['hash'].unique()

# ls_final=[]
# for el in unique_hash_ls:
#   df_hash = df_new[df_new['hash'] ==el]
#   mode = df_hash['Cat2_predicted'].mode()[0]

#   ls_final.append(mode)

# cat_label =inference.cat_label
# print(cat_label)
# ls_final_class =[k for el in tqdm(ls_final) for k in inference.cat_label.keys() if(el ==inference.cat_label[k])]

In [ ]:
# ls_final_class =[k for el in ls_final for k in cat_label.keys() if(el ==cat_label[k])]

In [ ]:
# predicted_class_df =inference.df_updated

# actual_ls= list(predicted_class_df['Cat2'])
# pred_ls = list(predicted_class_df['Cat2_predicted'])

# print(len(actual_ls))
# print(len(pred_ls))
# accuracy =accuracy_score(actual_ls, pred_ls)
# f1 =f1_score(actual_ls, pred_ls, average='weighted')
# print(accuracy)
# print(f1)

**level 3 classes**

In [ ]:
INPUT_DIR2 ='/gdrive/MyDrive/heirarchical_classifier_level_2'
test_excel_path2 ='/gdrive/MyDrive/heirarchical_classifier_level_1/heirarchical_classifier_cat2_pred.xlsx'
# cat_lab_path ='/gdrive/MyDrive/heirarchical_classifier_level_1/cat_label_map.json'

MAX_LEN =512

In [ ]:
df_test2 = pd.read_excel(test_excel_path2, engine='openpyxl')

In [ ]:
df_test2.head()

    productId  ...        Cat2_predicted
0  B0002AQK70  ...                  cats
1  B0002DK8OI  ...  bunny rabbit central
2  B0006VJ6TO  ...           health care
3  B000EZSFXA  ...            snack food
4  B000KV61FC  ...                  dogs

[5 rows x 10 columns]

Creating nested dict of primary-->secondary-->tertiary mapping

In [ ]:
di_prim_sec={}

level_zero_unique_class= list(df_test2['Cat1'].unique())
for prim_key in level_zero_unique_class:

  df_test2_sec = df_test2[df_test2['Cat1']==prim_key]

  level_one_unique_class =list(df_test2_sec['Cat2'].unique())

  di_sec_tert={}
  for sec_key in level_one_unique_class:

    df_test2_tert =df_test2_sec[df_test2_sec['Cat2'] ==sec_key]

    di_sec_tert[sec_key] = list(df_test2_tert['Cat3'].unique())

  di_prim_sec[prim_key] =di_sec_tert

In [ ]:
from pprint import pprint

In [ ]:
pprint(di_prim_sec)

{'baby products': {'bathing skin care': ['unknown',
                                         'soaps cleansers',
                                         'grooming healthcare kits',
                                         'shampoo',
                                         'skin care',
                                         'bathing tubs seats'],
                   'car seats accessories': ['accessories', 'car seats'],
                   'diapering': ['disposable diapers',
                                 'diaper stackers caddies',
                                 'diaper pails refills',
                                 'changing table pads covers',
                                 'diaper bags',
                                 'diaper changing kits',
                                 'cloth diapers',
                                 'unknown',
                                 'wipes holders'],
                   'feeding': ['breastfeeding',
                               'food',
                               'bottle feeding',
                               'highchairs booster seats',
                               'pillows stools',
                               'solid feeding',
                               'pacifiers accessories',
                               'unknown'],
                   'gear': ['backpacks carriers',
                            'swings',
                            'playards',
                            'walkers',
                            'activity centers entertainers',
                            'baby gyms playmats',
                            'baby seats',
                            'unknown'],
                   'gifts': ['toy banks', 'unknown', 'albums', 'keepsakes'],
                   'health baby care': ['teethers', 'sun protection'],
                   'nursery': ['unknown',
                               'nursery d cor',
                               'furniture',
                               'bedding'],
                   'potty training': ['step stools',
                                      'potties seats',
                                      'training pants'],
                   'pregnancy maternity': ['maternity pillows'],
                   'safety': ['edge corner guards',
                              'gates doorways',
                              'bathroom safety',
                              'monitors',
                              'kitchen safety',
                              'rails rail guards',
                              'harnesses leashes',
                              'electrical safety',
                              'cabinet locks straps',
                              'sleep positioners',
                              'unknown'],
                   'strollers': ['unknown',
                                 'tandem',
                                 'accessories',
                                 'lightweight',
                                 'standard']},
 'beauty': {'bath body': ['cleansers',
                          'scrubs body treatments',
                          'bath',
                          'bathing accessories',
                          'unknown',
                          'sets'],
            'fragrance': ['men s', 'unknown', 'women s', 'children s'],
            'hair care': ['hair color',
                          'styling tools',
                          'shampoos',
                          'unknown',
                          'styling products',
                          'conditioners',
                          'hair loss products',
                          'hair scalp treatments',
                          'shampoo conditioner sets',
                          'shampoo plus conditioner',
                          'hair relaxers'],
            'makeup': ['makeup remover',
                       'eyes',
                       'nails',
                       'lips',
                       'face',
                       'body',
                       'unknown'],
            'skin care': ['hands nails',
                          'face',
                          'unknown',
                          'body',
                          'sun',
                          'maternity',
                          'eyes',
                          'sets'],
            'tools accessories': ['makeup brushes tools',
                                  'bags cases',
                                  'nail tools',
                                  'mirrors',
                                  'hair coloring tools',
                                  'cotton swabs',
                                  'facial steamers',
                                  'unknown']},
 'grocery gourmet food': {'baby food': ['cereal', 'baby formula'],
                          'beverages': ['coconut water',
                                        'tea',
                                        'coffee',
                                        'soft drinks',
                                        'unknown',
                                        'powdered drink mixes',
                                        'water',
                                        'juices',
                                        'energy drinks',
                                        'hot cocoa',
                                        'sports drinks'],
                          'breads bakery': ['breadsticks',
                                            'cookies',
                                            'cakes',
                                            'fresh baked cookies',
                                            'unknown',
                                            'stuffing'],
                          'breakfast foods': ['cereals',
                                              'breakfast cereal bars',
                                              'toaster pastries'],
                          'candy chocolate': ['unknown',
                                              'mints',
                                              'hard candies',
                                              'chocolate assortments',
                                              'suckers lollipops',
                                              'chocolate bars',
                                              'gum',
                                              'gummy candies',
                                              'gummy candy',
                                              'licorice',
                                              'taffy',
                                              'fudge',
                                              'caramels',
                                              'chocolate truffles',
                                              'bars',
                                              'chewing gum',
                                              'jelly beans',
                                              'chocolate covered fruit',
                                              'nut clusters',
                                              'fruits',
                                              'chocolate covered nuts'],
                          'cooking baking supplies': ['baking mixes',
                                                      'chocolate',
                                                      'sugars sweeteners',
                                                      'nuts seeds',
                                                      'dessert toppings',
                                                      'coatings batters',
                                                      'flours meals',
                                                      'extracts flavoring',
                                                      'food coloring',
                                                      'sugar substitutes',
                                                      'unknown'],
                          'dairy eggs': ['unknown', 'milk', 'eggs', 'cheese'],
                          'fresh flowers live indoor plants': ['fresh cut '
                                                               'flowers',
                                                               'live indoor '
                                                               'plants'],
                          'gourmet gifts': ['snack gifts',
                                            'tea gifts',
                                            'chocolate gifts',
                                            'candy gifts',
                                            'seafood gifts',
                                            'meat gifts',
                                            'sauces gifts',
                                            'cheese gifts'],
                          'herbs': ['spices seasonings'],
                          'meat poultry': ['unknown', 'lamb', 'pork'],
                          'meat seafood': ['seafood'],
                          'pantry staples': ['herbs',
                                             'sauces',
                                             'dried beans',
                                             'cooking baking supplies',
                                             'canned jarred food',
                                             'jams',
                                             'pasta noodles',
                                             'unknown',
                                             'condiments',
                                             'packaged meals side dishes',
                                             'oils'],
                          'produce': ['fresh fruits', 'fresh vegetables'],
                          'sauces dips': ['sauces', 'dips'],
                          'snack food': ['jerky dried meats',
                                         'fruit leather',
                                         'crackers',
                                         'popcorn',
                                         'cookies',
                                         'pretzels',
                                         'salsas',
                                         'dried fruit',
                                         'chips',
                                         'party mix',
                                         'puffed snacks',
                                         'chips crisps',
                                         'unknown',
                                         'dried fruit raisins',
                                         'pork rinds']},
 'health personal care': {'baby child care': ['health care',
                                              'unknown',
                                              'personal care'],
                          'health care': ['massage relaxation',
                                          'foot care',
                                          'unknown',
                                          'family planning contraceptives',
                                          'first aid',
                                          'pill cases splitters',
                                          'pain relievers',
                                          'alternative medicine',
                                          'allergy',
                                          'women s health',
                                          'incontinence',
                                          'stress reduction',
                                          'smoking cessation',
                                          'digestion nausea',
                                          'cough cold',
                                          'diabetes',
                                          'sleep snoring',
                                          'stimulants',
                                          'thermometers',
                                          'therapeutic skin care',
                                          'thermometer accessories'],
                          'household supplies': ['household cleaning',
                                                 'cleaning tools',
                                                 'dishwashing',
                                                 'household batteries',
                                                 'unknown',
                                                 'paper plastic',
                                                 'air fresheners',
                                                 'laundry',
                                                 'lighters'],
                          'medical supplies equipment': ['braces',
                                                         'daily living aids',
                                                         'unknown',
                                                         'tests',
                                                         'mobility aids '
                                                         'equipment',
                                                         'occupational '
                                                         'physical therapy '
                                                         'aids',
                                                         'health monitors',
                                                         'beds accessories',
                                                         'bathroom aids '
                                                         'safety'],
                          'nutrition wellness': ['vitamins supplements',
                                                 'nutrition bars drinks',
                                                 'unknown',
                                                 'sports supplements',
                                                 'weight loss products'],
                          'personal care': ['shaving hair removal',
                                            'oral hygiene',
                                            'eye care',
                                            'unknown',
                                            'ear care',
                                            'deodorants antiperspirants',
                                            'lip care products',
                                            'foot care',
                                            'body art',
                                            'feminine care'],
                          'sexual wellness': ['bondage gear accessories',
                                              'safer sex',
                                              'adult toys games',
                                              'novelties',
                                              'sexual enhancers',
                                              'unknown',
                                              'sex furniture',
                                              'sensual delights']},
 'pet supplies': {'birds': ['food',
                            'feeding watering supplies',
                            'cages accessories',
                            'health supplies',
                            'toys',
                            'treats'],
                  'bunny rabbit central': ['food',
                                           'rabbit hutches',
                                           'houses habitats',
                                           'carriers',
                                           'feeding watering supplies',
                                           'treats'],
                  'cats': ['cat flaps',
                           'toys',
                           'litter housebreaking',
                           'food',
                           'beds furniture',
                           'feeding watering supplies',
                           'health supplies',
                           'carriers strollers',
                           'grooming',
                           'educational repellents',
                           'treats',
                           'collars'],
                  'dogs': ['toys',
                           'treats',
                           'litter housebreaking',
                           'grooming',
                           'beds furniture',
                           'collars',
                           'training behavior aids',
                           'carriers travel products',
                           'doors',
                           'houses',
                           'health supplies',
                           'apparel accessories',
                           'feeding watering supplies',
                           'food'],
                  'fish aquatic pets': ['aquarium heaters',
                                        'cleaners',
                                        'aquariums',
                                        'pumps filters',
                                        'automatic feeders',
                                        'aquarium d cor',
                                        'food',
                                        'aquarium starter kits',
                                        'aquarium lights',
                                        'test kits',
                                        'water treatments',
                                        'health supplies',
                                        'aquarium hoods',
                                        'hydrometers',
                                        'breeding tanks'],
                  'small animals': ['food',
                                    'houses habitats',
                                    'feeding watering supplies',
                                    'exercise wheels',
                                    'treats',
                                    'collars']},
 'toys games': {'action toy figures': ['figures',
                                       'playsets',
                                       'accessories',
                                       'statues'],
                'arts crafts': ['drawing painting supplies',
                                'craft kits',
                                'unknown',
                                'easels',
                                'stickers',
                                'drawing sketching tablets',
                                'aprons smocks',
                                'clay dough',
                                'blackboards whiteboards'],
                'baby toddler toys': ['blocks',
                                      'rattles',
                                      'teaching clocks',
                                      'bath toys',
                                      'stuffed animals toys',
                                      'stacking nesting toys',
                                      'unknown',
                                      'car seat stroller toys',
                                      'music sound',
                                      'push pull toys',
                                      'shape sorters',
                                      'activity play centers',
                                      'balls'],
                'building toys': ['building sets',
                                  'marble runs',
                                  'stacking blocks',
                                  'unknown'],
                'dolls accessories': ['dolls',
                                      'doll accessories',
                                      'dollhouses',
                                      'playsets',
                                      'dollhouse accessories'],
                'dress up pretend play': ['pretend play', 'beauty fashion'],

In [ ]:
class preprocessing2:

  def __init__(self, df):
    self.df =df
    self.filename = open(INPUT_DIR2+'/'+'cat_label_map.json', 'r')
    self.cat_label = json.load(self.filename)

    # print(INPUT_DIR1+'/'+self.first_level_class_mod)
    self.tokenizer =BertTokenizer.from_pretrained(INPUT_DIR2)
    self.model = BertForSequenceClassification.from_pretrained(INPUT_DIR2)
    self.model.cuda()

  def preprocess(self, level):
    if(level ==2):
      self.df_updated = self.df
      self.df_updated['Title'] = self.df_updated['Title'].fillna('')
      self.df_updated['Text'] = self.df_updated['Text'].fillna('')

      ls_new=[]
      for r in range(len(self.df_updated.axes[0])):
        di_temp = dict(self.df_updated.iloc[r])

        title =di_temp['Title']
        text = di_temp['Text']
        cat3 =di_temp['Cat3']
        pred_cat1 =di_temp['Cat1_predicted']
        pred_cat2 =di_temp['Cat2_predicted']

        st_hash = di_temp['productId']+di_temp['userId']+ str(di_temp['Time'])

        hash_ =hashlib.sha1(st_hash.encode('utf-8')).hexdigest()

        sent_list = sent_tokenize(text)

        for elm in sent_list:
          di_gran={}
          di_gran['hash'] =hash_
          di_gran['combined_text_granular'] =title+'. '+elm
          di_gran['Cat3'] = cat3
          di_gran['Cat1_predicted'] = pred_cat1
          di_gran['Cat2_predicted'] = pred_cat2

          ls_new.append(di_gran)


      self.df_new = pd.DataFrame(ls_new)

      X = list(self.df_new['combined_text_granular'])
      # Y = [self.cat_label[el] for el in list(self.df_new['Cat2'])]

    self.X =X
    # self.Y =Y

  def input_ids_converter(self):

    self.input_ids = []

    for sent in self.X:
      encoded_sent = self.tokenizer.encode(
                        sent,                      # Sentence to encode.
                        add_special_tokens = True)

      self.input_ids.append(encoded_sent)


    # print('Max sentence length: ', max([len(sen) for sen in self.input_ids]))


    self.input_ids = pad_sequences(self.input_ids, maxlen=MAX_LEN, dtype="long",
                          value=0, truncating="post", padding="post")


  def masking(self):

    self.attention_masks = []

    # For each sentence...
    for sent in self.input_ids:

        att_mask = [int(token_id > 0) for token_id in sent]

        # Store the attention mask for this sentence.
        self.attention_masks.append(att_mask)

  def input_convert(self):
    # Convert all inputs and labels into torch tensors, the required datatype
    # for our model.
    self.test_inputs = torch.tensor(self.input_ids)
    # self.test_labels = torch.tensor(self.Y)
    self.test_masks = torch.tensor(self.attention_masks)

    self.batch_size = 10
    # Create the DataLoader for our validation set.
    self.test_data = TensorDataset(self.test_inputs, self.test_masks)
    # self.test_data = TensorDataset(self.test_inputs, self.test_masks, self.test_labels)
    self.test_sampler = SequentialSampler(self.test_data)
    self.test_dataloader = DataLoader(self.test_data, sampler=self.test_sampler, batch_size=self.batch_size)


  # Function to calculate the accuracy of our predictions vs labels
  # def flat_accuracy(preds, labels, ls):
  #     pred_flat = np.argmax(preds, axis=1).flatten()
  #     ls+=list(pred_flat)
  #     labels_flat = labels.flatten()
  #     return np.sum(pred_flat == labels_flat) / len(labels_flat), ls

  # def weighted_f1(preds, labels):
  #     preds_flat = np.argmax(preds, axis=1).flatten()
  #     labels_flat = labels.flatten()
  #     return f1_score(labels_flat, preds_flat, average='weighted')

  def format_time(self,elapsed):
      '''
      Takes a time in seconds and returns a string hh:mm:ss
      '''
      # Round to the nearest second.
      elapsed_rounded = int(round((elapsed)))

      # Format as hh:mm:ss
      return str(datetime.timedelta(seconds=elapsed_rounded))

  # def model_initialize(self):
  #   model = BertForSequenceClassification(INPUT_DIR1+'/'+self.first_level_class_mod)
  #   model.cuda()
  #   return model


  def feed_forward(self):
    print("")
    print("Running testing...")

    t0 = time.time()

    # Put model in evaluation mode to evaluate loss on the validation set
    self.model.eval()

    # Tracking variables

    self.ls_new=[]
    eval_loss, eval_accuracy, eval_f1 = 0, 0, 0
    nb_eval_steps, nb_eval_examples = 0, 0

    # Evaluate data for one epoch
    for batch in tqdm(self.test_dataloader):
      # Add batch to GPU
      batch = tuple(t.to(device) for t in batch)

      # Unpack the inputs from our dataloader

      # b_input_ids, b_input_mask, b_labels = batch
      b_input_ids, b_input_mask = batch

      # Telling the model not to compute or store gradients, saving memory and speeding up validation
      with torch.no_grad():
        # Forward pass, calculate logit predictions
        # token_type_ids is for the segment ids, but we only have a single sentence here.
        # See https://github.com/huggingface/transformers/blob/5bfcd0485ece086ebcbed2d008813037968a9e58/examples/run_glue.py#L258
        outputs = self.model(b_input_ids, token_type_ids=None, attention_mask=b_input_mask)

      logits = outputs[0]

      # Move logits and labels to CPU
      logits = logits.detach().cpu().numpy()
      # label_ids = b_labels.to('cpu').numpy()

      self.ls_new+=list(logits)
      # Calculate the accuracy for this batch of test sentences.
      # tmp_eval_accuracy,self.ls_new  = flat_accuracy(logits, label_ids, self.ls_new)

      # Accumulate the total accuracy.
      # eval_accuracy += tmp_eval_accuracy

      #Calculate the f1 for this batch and accumulate it
      # temp_weighted_f1 = weighted_f1(logits, label_ids)
      # eval_f1 +=temp_weighted_f1

      # Track the number of batches
      nb_eval_steps += 1

    # pred_flat = np.argmax(logits, axis=1).flatten()
    # label_flat =label_ids.flatten()

    # new_f1 =f1_score(label_flat, pred_flat, average='weighted')

    # new_f1 = eval_f1/nb_eval_steps
    # accuracy = eval_accuracy/nb_eval_steps
    # # Report the final accuracy for this validation run.
    # print("  Accuracy: {0:.2f}".format(eval_accuracy/nb_eval_steps))
    # print("f1:-", new_f1)

    print("  Validation took: {:}".format(self.format_time(time.time() - t0)))


  def postprocessing(self):
    self.df_new['logits'] = self.ls_new

    unique_hash_ls =self.df_new['hash'].unique()

    ls_final, class_indx=[],[]
    for el in unique_hash_ls:
      df_hash = self.df_new[self.df_new['hash'] ==el]
      list_logits =df_hash['logits'].tolist()

      zero_shp = list_logits[0].shape
      zero_array =np.zeros(zero_shp)

      sum=zero_array
      for elm in list_logits:
        sum = np.add(elm, sum)

      ##method to check the most prior in context to given cat1 and cat2 predictions
      average_sum = sum/len(list_logits)

      sorted_avg = np.sort(average_sum)[::-1]

      index_priority=[]

      for el_ in sorted_avg:
        indx = int(np.where(average_sum ==el_)[0][0])
        index_priority.append(indx)

      cat1 = df_hash['Cat1_predicted'].unique().tolist()[0]
      cat2 = df_hash['Cat2_predicted'].unique().tolist()[0]

      tert_categories = di_prim_sec[cat1][cat2]

      tert_classes =[self.cat_label[category] for category in tert_categories]

      for idx in range(len(index_priority)):
        if(index_priority[idx] in tert_classes):
          ls_final.append(index_priority[idx])
          class_indx.append(idx)
          break




    ls_final_class =[k for el in tqdm(ls_final) for k in self.cat_label.keys() if(el ==self.cat_label[k])]
    self.df_updated['Cat3_predicted'] =ls_final_class
    self.df_updated['Cat3_class_priority_index'] = class_indx

    # print(ls_final_class)
    # print(class_indx)

In [ ]:
inference =preprocessing2(df_test2)
inference.preprocess(2)
inference.input_ids_converter()
inference.masking()
inference.input_convert()
inference.feed_forward()

# inference.postprocessing()

Token indices sequence length is longer than the specified maximum sequence length for this model (530 > 512). Running this sequence through the model will result in indexing errors

Running testing...

100%|██████████| 4062/4062 [25:35<00:00,  2.65it/s]

  Validation took: 0:25:35

In [ ]:
inference.postprocessing()

100%|██████████| 10000/10000 [00:00<00:00, 29497.07it/s]

NameError: ignored

In [ ]:
inference.df_updated.head()

    productId  ...      Cat3_predicted
0  B0002AQK70  ...           cat flaps
1  B0002DK8OI  ...              treats
2  B0006VJ6TO  ...  massage relaxation
3  B000EZSFXA  ...   jerky dried meats
4  B000KV61FC  ...                toys

[5 rows x 11 columns]

In [ ]:
df_new =inference.df_new
df_updated = inference.df_updated
unique_hash_ls =df_new['hash'].unique()

ls_final, class_indx=[],[]
for el in unique_hash_ls:
  df_hash = df_new[df_new['hash'] ==el]
  list_logits =df_hash['logits'].tolist()

  zero_shp = list_logits[0].shape
  zero_array =np.zeros(zero_shp)

  sum=zero_array
  for elm in list_logits:
    sum = np.add(elm, sum)

  average_sum = sum/len(list_logits)

  sorted_avg = np.sort(average_sum)[::-1]

  index_priority=[]

  for el_ in sorted_avg:
    indx = int(np.where(average_sum ==el_)[0][0])
    index_priority.append(indx)

  cat1 = df_hash['Cat1_predicted'].unique().tolist()[0]
  cat2 = df_hash['Cat2_predicted'].unique().tolist()[0]

  tert_categories = di_prim_sec[cat1][cat2]

  tert_classes =[inference.cat_label[category] for category in tert_categories]

  for idx in range(len(index_priority)):
    if(index_priority[idx] in tert_classes):
      ls_final.append(index_priority[idx])
      class_indx.append(idx)
      break




ls_final_class =[k for el in tqdm(ls_final) for k in inference.cat_label.keys() if(el ==inference.cat_label[k])]
df_updated['Cat3_predicted'] =ls_final_class
df_updated['Cat3_class_priority_index'] = class_indx

  0%|          | 0/10000 [00:00<?, ?it/s]
 23%|██▎       | 2296/10000 [00:00<00:00, 22953.24it/s]
 48%|████▊     | 4764/10000 [00:00<00:00, 23965.88it/s]
 72%|███████▏  | 7228/10000 [00:00<00:00, 24270.36it/s]
100%|██████████| 10000/10000 [00:00<00:00, 23932.58it/s]

In [ ]:
df_updated.head(10)

    productId  ... Cat3_class_priority_index
0  B0002AQK70  ...                         0
1  B0002DK8OI  ...                         0
2  B0006VJ6TO  ...                         0
3  B000EZSFXA  ...                         0
4  B000KV61FC  ...                         0
5  B000JQALAE  ...                         0
6  B000JCCVQU  ...                         0
7  B000TA8MKG  ...                         0
8  B000093A0U  ...                         0
9  B000N2Q1V2  ...                         0

[10 rows x 12 columns]

In [ ]:
actual_ls= list(df_updated['Cat3'])
pred_ls = list(df_updated['Cat3_predicted'])

print(len(actual_ls))
print(len(pred_ls))
accuracy =accuracy_score(actual_ls, pred_ls)
f1 =f1_score(actual_ls, pred_ls, average='weighted')
print(accuracy)
print(f1)

10000
10000
0.9689
0.9687911283117574

In [ ]:
df_updated.to_excel(INPUT_DIR2+'/'+'heirarchical_classifier_cat3_pred.xlsx', index=False)

Overall accuracy considering the correctness of all three categories

In [ ]:
sequence_correction_num =0
for idx in range(len(df_updated.axes[0])):
  di_idx = dict(df_updated.iloc[idx])

  if((di_idx['Cat1'] ==di_idx['Cat1_predicted']) and (di_idx['Cat2'] ==di_idx['Cat2_predicted']) and (di_idx['Cat3'] ==di_idx['Cat3_predicted']) ):
    sequence_correction_num+=1

print('overall_accuracy:-{0}'.format(sequence_correction_num/len(df_updated.axes[0])))

overall_accuracy:-0.965